const data = [
  {
    id: 1,
    img: "https://i.ibb.co/0QbcYBS/Aire-acondicionado-Split-Kanji-2600w-f-c-26fkht81.jpg",
    title: "Aire Acondicionado Split KANJI 2600w FC",
    price: "$00.00",
    category: "aire",
    marca: "KANJI",
    modelo: "26FKHT81",
    deflectoresmoviles: "Sí",
    frigorias: "2240",
    display: "No",
    timer: "Sí",
    automatico: "Si",
    sleep: "Sí",
    ventilacion: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    contro: "Sí",
    inverter: "No",
    gas: "R-410a",
    detail: "Aire Acondicionada Kanji Split 2600 watts frio-calor consumo A. El equipo Kanji cuenta con eficiencia energética clase A, que permite reducir el consumo de energía hasta un 16 por ciento (vs. un equipo similar de eficiencia energética C.) También, utiliza el gas no tóxico y no contaminante R410A, que no contribuye al debilitamiento de la capa de ozono y tiene una mayor capacidad de refrigeración.",
  },
  {
    id: 2,
    img: "https://i.ibb.co/pKCPbxc/aire-acondicionado-split-hitachi-2600w-fc.jpg",
    title: "Aire Acondicionado Split HITACHI 2600w FC",
    price: "$00,00",
    category: "aire",
    marca: "HITACHI",
    tipo_equipo: "Split",
    frio_calor: "Sí",
    frigorias: "2499",
    gas: "R410A",
    tipo_energia: "A",
    automático: "Sí",
    deshumificación: "Sí",
    sleep: "Sí",
    medidasSplit: "27,5cm Alto - 85cm Ancho - 32cm Prof.",
    peso: "11 kg",
    medidasMotor: "54,5cm Alto - 70cm Ancho - 30cm Prof.",
    pesoMotor: "27 kg",
    control: "Sí",
    detail: "El aire acondicionado Split Frío/Calor HSEL2600FC tiene 2236 frigorías y 2600 watts de potencia. Para elegir el equipo adecuado, hay que tener en cuenta los metros cuadrados de la habitación donde va a instalarse. Además, la orientación de la casa/depto; la cantidad de personas que usan la habitación; el número de ventanas y la cantidad aparatos eléctricos que hay.",
  },

  {
    id: 3,
    img: "https://i.ibb.co/g9mKHqb/aire-acondicionado-split-kanji-3200w-fc.jpg",
    title: "Aire acondicionado Split KANJI 3200w FC",
    price: "$00,00",
    category: "imagen",
    marca: "KANJI",
    display: "No",
    deflectores_moviles: "Sí",
    frigorias: "2760",
    timer: "Sí",
    automatico: "Sí",
    sleep: "Sí",
    ventilación: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    control: "Sí",
    inverter: "No",
    gas: "R-410a",
    detail: "Aire Acondicionada Kanji Split 3200 watts frio-calor consumo A. El equipo Kanji cuenta con eficiencia energética clase A, que permite reducir el consumo de energía hasta un 16 por ciento (vs. un equipo similar de eficiencia energética C.) También, utiliza el gas no tóxico y no contaminante R410A, que no contribuye al debilitamiento de la capa de ozono y tiene una mayor capacidad de refrigeración.",
  },
  {
    id: 4,
    img: "https://i.ibb.co/r67MbZ3/aire-acondicionado-inverter-greenstay-fc-3500.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 3500w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "3010",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
    detail: "Climatizar tus espacios a lo largo del año es algo importante para tu comodidad. Un aire acondicionado frío/calor Inverter es la mejor decisión, ya que conseguís una mejor relación costo-beneficio.Diseño adecuado a tus espacios. El tipo de aire split es de bajo consumo energético, de fácil mantenimiento y sumamente silencioso ya que cuenta con una unidad exterior.Reducción de humedad y temperatura constante.El deshumidificador absorbe el agua del aire y disminuye la molesta humedad, creando un ambiente confortable y de calidad.La tecnología inverter mejora la eficiencia de tu equipo, potencia su capacidad de refrigeración y proporciona una temperatura más estable. Programa de acuerdo a tus necesidades. Cuando las personas descansan su temperatura corporal baja gradualmente. Por eso, este aire cuenta con la función sleep, que hace que la temperatura del ambiente aumente a medida que pasa el tiempo. No tendrás que levantarte a apagarlo y podrás disfrutar de un sueño placentero.",
  },
  {
    id: 5,
    img: "https://i.ibb.co/HHG7r1D/aire-acondicionado-inverter-greenstay-fc-6900.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 6900w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "5934",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
    detail: "Programa de acuerdo a tus necesidades. Cuando las personas descansan su temperatura corporal baja gradualmente. Por eso, este aire cuenta con la función sleep, que hace que la temperatura del ambiente aumente a medida que pasa el tiempo. No tendrás que levantarte a apagarlo y podrás disfrutar de un sueño placentero. Potencia de refrigeración 6900 Watts. Tipo de aire acondicionado Split. Lugares de colocación De pared. Tipo de climatización Frío/Calor. Eficiencia energética A+. Capacidad de refrigeración 6.9 W. Capacidad de calefacción 6.9 W. Frigorías 5934 fg. Tipo de gas refrigerante R-410A. Eficiencia energética: A+",
  },
  {
    id: 6,
    img: "https://i.ibb.co/TLkWf51/ventilador-vitta-18pulgadas-3-en-1-90w.jpg",
    title: "Ventilador VITTA 18'' 3 en 1 90w",
    price: "$00,00",
    category: "ventilacion",
    marca: "VITTA",
    dimensiones: "46cm",
    tipo_ventilador: "Mesa, Pared, Pie",
    potencia: "90 w",
    velocidades: "3",
    aspas: "Metal",
    cantidad_aspas: "3",
    detail: "¡Aire limpio y fresco en tus ambientes! El ventilador VITTA 18'' 3 en 1 es un elemento útil para dar frescura en el hogar. Con su óptimo rendimiento, la sensación térmica disminuirá. Es un aparato práctico, fácil de armar e instalar. Composición perfecta. Con sus palas elaboradas en metal vas a poder disfrutar de un producto de alta calidad y durabilidad. Su estilo único resalta en cualquier ámbito debido a su óptimo funcionamiento. Para una cobertura mayor de espacios, su oscilación de 180º proporciona un flujo constante de aire que permite refrescar más eficientemente los ambientes.Hacele frente al verano de la mano de este potente ventilador con función 3 en 1. Sus paletas metálicas y su motor de alta potencia te aseguran comodidad y confort para vos y tu familia. Además, tenes la posibilidad de usarlo tanto como ventilador de pie, como turbo o como ventilador de pared. Su pie es robusto y asegura la estabilidad del mismo. Su diámetro es de 18",
  },
  {
    id: 7,
    img: "https://i.ibb.co/7V2dS40/ventilador-industrial-vitta-30-Pulgadas-2-en-1.jpg",
    title: "Ventilador Industrial Vitta 30'' 2 en 1",
    price: "$00,00",
    category: "ventilacion",
    marca: "VITTA",
    tipo_ventilador: "Pared, Pie",
    cantidad_aspas: "3",
    velocidades: "3",
    altura: "1,4 metros",
    potencia: "180W",
    aspas: "Plásticas",
    detail: "Su funcionamiento está adaptado e ideado para entornos industriales. Esto hace que los distintos gases y aromas sean removidos sin inconvenientes. A su vez, tiene la capacidad de resistir ambientes severos, sin verse afectado por altas temperaturas ni presiones. Composición perfecta: para una cobertura mayor de espacios, su oscilación de 180º proporciona un flujo constante de aire que permite refrescar más eficientemente los ambientes.",
  },
  {
    id: 8,
    img: "https://i.ibb.co/N6LrtJg/Ventilador-18-Pulgadas-3-en-1-STAR-TRAK.jpg",
    title: "Ventilador 18'' 3 en 1 STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Metal",
    potencia: "90W",
    detail: "¡Aire limpio y fresco en tus ambientes! El ventilador Star Trak STP31-18 es un elemento útil para dar frescura en el hogar. Con su óptimo rendimiento, la sensación térmica disminuirá. Es un aparato práctico, fácil de armar e instalar. Composición perfecta. Con sus palas elaboradas en metal vas a poder disfrutar de un producto de alta calidad y durabilidad. Su estilo único resalta en cualquier ámbito debido a su óptimo funcionamiento. Para una cobertura mayor de espacios, su oscilación de 180º proporciona un flujo constante de aire que permite refrescar más eficientemente los ambientes.",
  },
  {
    id: 9,
    img: "https://i.ibb.co/MgJGJFf/Ventilador-Pie-14-Pulgadas-Base-Pesada-STAR-TRAK.jpghttps://picsum.photos/200/300?random=9",
    title: "Ventilador Pie 14'' Base Pesada STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos",
    detail: "Ventilador de pie Star Trak de 14 pulgadas PRODUCTO NUEVO EN CAJA CERRADA, CON GARANTIA. Hacemos factura A o B Modelo: STPG14 Características: -Motor de 90 watts. Bobinado 100% cobre. -3 niveles de potencia -Reja giratoria -1,50 mts de altura máxima -Base volante -Aspa plástica de 5 palas hélices -Cabezal reclinable",
  },
  {
    id: 10,
    img: "https://i.ibb.co/WBR7xrp/Ventilador-Pie-14-Pulgadas-STAR-TRAK-Multi.jpg",
    title: "Ventilador Pie 14'' STAR TRAK Multi",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos",
  },
  {
    id: 11,
    img: "https://i.ibb.co/kcJYp06/Ventilador-14-Pulgadas-STAR-TRAK.jpg",
    title: "Ventilador 20'' STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,70 Metros",
    potencia: "120W",
    otro: "Repele Mosquitos",
  },
  {
    id: 12,
    img: "https://i.ibb.co/bdQqNYr/Climatizador-Philco-Portatil-7-L.jpg",
    title: "Climatizador Philco Portatil 7L",
    price: "$00,00",
    category: "calefaccion",
    marca: "PHILCO",
    velocidades: "3",
    tipo_equipo: "Oscilación",
    otro: "No requiere instalación",
    flujo_aire: "600 m3/h",
    cantidad_agua: "7 Lts (5 Lts con los cubos de hielo reutilizables)",
    detalles: "Indicador de nivel de agua",
    timer: "No",
    peso: "6,6 kgs",
    dimesion: "Alto: 70 cm Ancho: 28 cm Prof: 26,5 cm",
  },
  {
    id: 13,
    img: "https://i.ibb.co/B2h9Vv3/Climatizador-Kanji-LRG04-11-CR-Frio-Calor.jpg",
    title: "Climatizador Kanji LRG04-11CR Frio Calor",
    price: "$00,00",
    category: "calefaccion",
    marca: "KANJI",
    velocidades: "3",
    frio_calor: "Si",
    control: "Si",
    cantidad_agua: "8 Litros",
    dimensiones: "Alto 70 cm Ancho 37 cm Prof: 29 cm",
  },
  {
    id: 14,
    img: "https://i.ibb.co/nL5qRNX/Heladera-Briket-322-L-BK2-F-1610-Blanca-Gris-Negro.jpg",
    title: "Heladera Briket 322L BK2F 1610 Blanca-Gris-Negro",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "BK2F 1610",
    color: "Blanco, Gris o Negro",
    freezer: "Superior",
    estantes_freezer: "1",
    dimensiones: "Ancho: 66cm Altura: 164cm Prof: 682cm",
    estantes_heladera: "3",
    dispenser_agua: "No",
    dispenser_hielo: "No",
    luz_interior: "Si",
    cantidad_puertas: "2",
    inverter: "No",
    tipo_energia: "A+",
    capacidad: "322 Litros",
    congelador: "No",
    vegetales: "Si",
    porta_botellas: "No",
    porta_latas: "No",
    porta_huevos: "Si",
  },
  {
    id: 15,
    img: "https://i.ibb.co/F0wyRpN/Heladera-Briket-476-L-BK2-F-2121-Gris.jpg",
    title: "Heladera Briket 476L BK2F 2121 Gris",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    Modelo: "BK2F 2121",
    dimensiones: "Ancho: 66cm x Prof: 75cm x Alto: 189 cm",
    inverter: "No",
    tipo_energia: "A+",
    deshielo: "Manual",
    freezer: "Superior",
    luz_interior: "Sí",
    puertas: "2",
  },
  {
    id: 16,
    img: "https://i.ibb.co/1X2pcjr/Heladera-SIAM-Top-Mount-370l-C-Disp-inox.jpg",
    title: "Heladera SIAM Top Mount 370l C-Disp inox",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "SIAM",
    modelo: "HSI-NT30XD",
    estilo: "Acero inoxidable",
    freezer: "Superior",
    estantes_freezer: "1",
    fabrica_hielo: "Si",
    peso: "68 Kg",
    dimensiones: "Ancho: 69.6cm Prof: 68.5cm Alto: 171.2cm",
    estantes_heladera: "3",
    dispenser_agua: "Si",
    dispenser_hielo: "Si",
    luz_interior: "Si",
    inverter: "Si",
    deshielo: "No Frost",
    tipo_energia: "A",
    capacidad: "404 Litros",
    niveles_temperatura: "6",
    porta_vegetales: "Si",
    cantidad_puertas: "2",
    display: "No",
  },
  {
    id: 17,
    img: "https://i.ibb.co/d4rRygF/Heladera-Samsung-Inox-321-L-con-display-RT32-K5930-SL.jpg",
    title: "Heladera Samsung Inox 321L con display RT32K5930SL",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "SAMSUNG",
    modelo: "Rt32k5930sl",
    inverter: "Si",
    dimensiones: "Ancho: 60cm, Prof.: 67.2cm Alto: 171.5cm",
    luz_interior: "Si",
    tipo_energia: "A+",
    enfriamiento: "No Frost",
    cantidad_puertas: "2",
    estantes_regulables: "Si",
    porta_vegetales: "Si",
    capacidad: "320 Litros",
    capacidad_freezer: "72 Litros",
    porta_botellas: "No",
    display: "Si",
    fabrica_hielo: "Si",
    dispenser_agua: "Si",
  },
  {
    id: 18,
    img: "https://i.ibb.co/rMyxDZq/Heladera-Samsung-Inox-380-L-Con-Display-RT38-K5932-SL.jpg",
    title: "Heladera Samsung Inox 380L Con Display RT38K5932SL",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "SAMSUNG",
    modelo: "RT38K5982SL/B3",
    capacidad: "394 L",
    inverter: "Sí",
    tipo_energia: "A+",
    deshielo: "No frost",
    freezer: "Superior",
    estantes_freezer: "1",
    fabrica_hielo: "Si",
    peso: "72 KG",
    dimensiones: "Ancho: 67.5cm Prof.: 66.8cm Alto: 178.5cm",
    niveles_temperatura: "5",
    porta_vegetales: "Si",
    porta_huevos: "Si",
    puertas: "2",
    display: "Si",
    sistema_air_flow: "Si",
    filtro_desodorizador: "Si",
  },
  {
    id: 19,
    img: "https://i.ibb.co/BBvMzwk/Heladera-Philco-Inox-530l-94phsb530xt.jpg",
    title: "Heladera Philco Inox 530l 94phsb530xt",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "PHILCO",
    modelo: "PHSB530XT",
    capacidad: "282 L",
    inverter: "No",
    tipo_energia: "A+",
    capacidad_freezer: "218 L",
    deshielo: "No frost",
    freezer: "Side by side",
    estantes_freezer: "2",
    fabrica_hielo: "No",
    peso: "99 Kg",
    dimensiones: "Ancho: 89,5cm Prof.: 74,5cm Alto: 178,8cm",
    porta_vegetales: "Sí",
    puertas: "2",
    display: "Sí",
    sistema_air_flow: "Sí",
  },
  {
    id: 20,
    img: "https://i.ibb.co/R0xKjJ0/Heladera-BRIKET-Bajo-Mesada.jpg",
    title: "Heladera BRIKET Bajo Mesada Colores",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    dimensiones: "Ancho: 55cm, Prof.: 62cm Alto: 85cm",
    peso: "3 Kg",
    capacidad: "146 Litros",
    tipo_energia: "A",
    porta_latas: "No",
    fabrica_hielo: "No",
    dispenser: "No",
    porta_vegetales: "Si",
  },
  {
    id: 21,
    img: "https://i.ibb.co/g6p4V0H/Freezer-Horizontal-Briket-FR-2500-st.jpg",
    title: "Freezer Horizontal Briket FR 2500 st",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "FR 2500",
    capacidad: "224 L",
    ruedas: "Si",
    funciones: "Enfriar, Freezar",
    tipo_energia: "B",
    peso: "50.1 Kg",
    dimensiones: "Ancho: 94,5cm Prof.: 70cm Ancho: 84cm",
    orientacion: "Horizontal",
    cantidad_puertas: "1",
  },
  {
    id: 22,
    img: "https://picsum.photos/200/300?random=10",
    title: "Freezer Horizontal Briket FR 3300 ST",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "FT 3300 ST",
    capacidad: "295 Litros",
    peso: "40 KG",
    dimensiones: "Alto: 84cm Prof.: 70cm Ancho: 115,5cm",
    orientacion: "Horizontal",
    cantidad_puertas: "1",
    cestos_deslizables: "Si",
    enfriador_botellas: "Si",
  },
  {
    id: 23,
    img: "https://i.ibb.co/8P8xJ2t/Freezer-Horizontal-Briket-FR-4500-ST-2-Puertas.jpg",
    title: "Freezer Horizontal Briket FR 4500 ST 2 Puertas",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "FR 4500",
    capacidad: "390 L",
    ruedas: "Sí",
    funciones: "Congelar, Conservar, Enfriar",
    tipo_energia: "A",
    peso: "64.4 KG",
    dimensiones: "Ancho: 148cm Prof.: 70cm Alto: 84cm",
    orientacion: "Horizontal",
    cantidad_puertas: "2",
    cantidad_cajones: "2",
  },
  {
    id: 24,
    img: "https://i.ibb.co/k6cGWnF/Exhibidora-Comercial-BRIKET-Master-3200.jpg",
    title: "Exhibidora Comercial BRIKET Master 3200",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    capacidad: "315 Litros",
    dimensiones: "Ancho: 55cm Prof.: 63cm Alto c/Cenefa: 185.5cm Alto s/Cenefa: 171cm",
    cantidad_puertas: "Triple vidrio Deshidratado entre sí",
    luz_interior: "Si",
    cantidad_estantes: "4 Intercambiables",
    motocompresor: "1/3 HP reforzado",
    niveles_temperatura: "de 0° a +5° C",
    otro: "Ideal para bebidas, lácteos, frutas, verduras, pastas, etc",
  },
  {
    id: 25,
    img: "https://i.ibb.co/HHgybCC/Exhibidora-Comercial-BRIKET-Master-4300.jpg",
    title: "Exhibidora Comercial BRIKET Master 4300",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    capacidad: "417 Litros",
    cantidad_estantes: "4",
    max_estante: "42 Kg",
    tipo_energia: "D",
    gas: "R 290",
    dimensiones: "Ancho: 65,5cm Prof.: 60cm Alto: 203cm",
    peso: "79 Kg",
  },
  {
    id: 26,
    img: "https://i.ibb.co/PYLQv7R/Exhibidora-Comercial-BRIKET-Master-5000.jpg",
    title: "Exhibidora Comercial BRIKET Master 5000",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    peso: "95 KG",
    dimensiones: "Ancho: 70cm Prof.: 62cm Alto: 208cm",
    capacidad: "501 Litros",
    cantidad_puertas: "Triple vidrio",
    cantidad_estantes: "4 Estantes Removibles",
    motocompresor: "1/3 Hp",
    niveles_temperatura: "0 a +5°C",
  },
  {
    id: 27,
    img: "https://i.ibb.co/dMVXvjY/Exhibidora-Comercial-Best-Cold-2-Puertas-750l-MT750.webp",
    title: "Exhibidora Comercial BestCold 2 Puertas 750l MT750",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "MT750",
    capacidad: "750 L",
    orientacion: "Vertical",
    luz_interior: "Sí",
    dimensiones: "Alto: 180cm Prof.: 65cm Ancho: 110cm",
    control_temperatura: "Sí",
    niveles_temperatura: "4 °C - 10 °C",
    cervecera: "Sí",
    cantidad_puertas: "2",
    tipo_puertas: "Batientes",
    descongelamiento: "Automatico",
    motocompresor: "1/3 hp",
  },
  {
    id: 28,
    img: "https://i.ibb.co/9wwKbfT/Freezer-Horizontal-BRIKET-Tapa-Vidrio-3300.jpg",
    title: "Freezer Horizontal BRIKET Tapa Vidrio 3300",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "EH 3300",
    capacidad: "295 L",
    orientacion: "Horizontal",
    cantidad_cajones: "2",
    ruedas: "Sí",
    dimensiones: "Alto: 95cm Prof.: 61cm Ancho 115.5cm",
    tipo_energia: "A",
    gas: "R134",
    motocompresor: "FF1-12HBK",
  },
  {
    id: 29,
    img: "https://i.ibb.co/0cffVH7/Freezer-Horizontal-Teora-550-L-TV-FH550-TV.jpg",
    title: "Freezer Horizontal TEORA 550L TV FH550TV",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "TEORA",
    modelo: "FH550TV",
    capacidad: "542 L",
    cantidad_puertas: "2",
    cantidad_cajones: "2",
    dimensiones: "Ancho: 162cm Prof.: 70cm Alto: 84cm",
    niveles_temperatura: "-18°C a +5°C",
    gas: "R-134a",
  },
  {
    id: 30,
    img: "https://i.ibb.co/1nY1FH9/Batea-Comercial-Best-Cold-Standard-Recta-2400-R.jpg",
    title: "Batea Comercial BestCold Standard Recta 2400-R",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "2400-R",
    dimensiones: "Alto: 135cm Prof.: 100cm Ancho: 240cm",
    tipo_gabinete: "Exterior en Chapa",
    termoformado: "Alto Impacto",
    mesa_trabajo: "Acero Inoxidable Brillante",
    luz_interior: "Si",
    gas: "R22",
    otro: "Ideal para Granja, Carniceria, Pescaderia",
  },
  {
    id: 31,
    img: "https://i.ibb.co/RNRTRdr/Vitrina-Mostrador-BESTCOLD-Winnipeg-610-L-1600-WE.jpg",
    title: "Vitrina Mostrador BESTCOLD Winnipeg 610L 1600WE",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "winnipeg 1200",
    capacidad: "240 L",
    orientación: "Horizontal",
    luz_interior: "Sí",
    dimensiones: "Alto: 113cm Prof.: 78cm Ancho: 120cm",
    control_temperatura: "Sí",
    niveles_temperatura: "2 °C - 10 °C",
    cervecera: "Sí",
    material: "Acero",
  },
  {
    id: 32,
    img: "https://i.ibb.co/gj4QR3W/Batea-Comercial-Best-Cold-standard-Vidrio-bajo-1300-rs.jpg",
    title: "Batea Comercial BestCold standard Vidrio bajo 1300-RS",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "1300-RS",
    orientación: "Horizontal",
    luz_interior: "Sí",
    control_temperatura: "Sí",
    niveles_temperatura: "2 °C - 10 °C",
    material: "Acero"
  },
  {
    id: 33,
    img: "https://i.ibb.co/7kM7Cwj/Vitrina-Best-Cold-Winnipeg-Dark-1400-WE.jpg",
    title: "Vitrina BestCold Winnipeg Dark 1400WE",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "Winnipeg Dark 1400WE",
    mesa_trabajo: "Acero Inoxidable",
    termoformado: "Alto impacto",
    cantidad_estantes: "3",
    tipo_puertas: "Batientes Automáticas",
    luz_interior: "Si",
    niveles_temperatura: "2º a 6º c",
    motocompresor: "Embraco 1/4 HP",
    dimensiones: "Ancho: 140 cm. Prof.: 75 cm. Alto: 119 cm",
  },
  {
    id: 34,
    img: "https://i.ibb.co/gy6d8R9/Vitrina-con-Bajada-Best-Cold-450-L-1700-E.jpg",
    title: "Vitrina con Bajada BestCold 450L 1700E",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "2100E",
    dimensiones: "Alto: 113cm Prof.: 78cm Ancho: 210cm",
    mesa_trabajo: "Acero Inoxidable",
    termoformado: "Alto Impacto",
    tipo_puertas: "Batientes",
    control_temperatura: "Digital con Descongelamiento Automatico",
    luz_interior: "Si, Tecnologia LED",
  },
  {
    id: 35,
    img: "https://i.ibb.co/Xs77jkx/Lavarropas-Drean-Next-8-12-ECO.jpg",
    title: "Lavarropas Drean Next 8.12 ECO",
    price: "$00,00",
    category: "lavarropas",
    marca: "DREAN",
    modelo: "8.12 ECO",
    velocidad_centrifugado: "1200 rpm",
    centrifugado: "Sí",
    centrifugado_autoequilibrado: "Sí",
    peso: "71 KG",
    dimensiones: "Alto:	85cm Prof.:	55cm Ancho:	60cm",
    filtro: "Sí",
    tambores: "1 de Acero Inoxidable",
    tipo_lavarropas: "Automatico",
    carga: "Frontal",
    tipo_energia: "A++",
    capacidad: "8 KG",
    lavasecarropas: "No",
    inverter: "No",
    smartphone: "No",
    alarma_final: "Si",
    wifi: "No",
    display: "Si, LED",
    tegnologia: "ECO",
    niveles_temperatura: "Fría, 30°C, 40°C, 60°C, 70°C",
    cantidad_programas: "34",
    tipo_bloqueo: "Bloqueo Panel, Bloqueo Seguridad de Puerta",
    otro: "Lavado Rapido, Funcion Antiarrugas",
  },
  {
    id: 36,
    img: "https://i.ibb.co/cgYJ1mC/Lavasecarropas-Electrolux-8kg-inverter-EWD08-B.png",
    title: "Lavasecarropas Electrolux 8kg inverter EWD08B",
    price: "$00,00",
    category: "lavarropas",
    marca: "ELECTROLUX",
    modelo: "EWD08B",
    dimensiones: "Alto: 85cm Prof.: 57.5cm Ancho: 60cm",
    lavasecarropas: "Sí",
    capacidad_secado: "5 Kg",
    inverter: "Si",
    capacidad: "8 kg",
    carga: "Frotal",
    tipo_energia: "A",
    velocidad_centrifugado: "1200 rpm",
    centrifugado: "Si",
    centrifugado_autoequilibrado: "Si",
    peso: "62.2 kg",
    filtro: "Si",
    tambor: "1, de Acero Inoxidable",
    display: "Si, tipo LED",
    tipo_bloqueo: "Bloqueo de Panel, Bloqueo de Seguridad de Puerta",
    otro: "Funcion Antiarrugas",
  },
  {
    id: 37,
    img: "https://i.ibb.co/D4gfFgd/Lavarropas-Drean-Concept-Fuzzy-Logic-Tech-V1.jpg",
    title: "Lavarropas Drean Concept Fuzzy Logic Tech V1",
    price: "$00,00",
    category: "lavarropas",
    marca: "DREAN",
    modelo: "Fuzzy Logic Tech V1",
    lavasecarropas: "No",
    carga: "Superior",
    tipo_energia: "B",
    capacidad: "5 Kg",
    inverter: "No",
    velocidad_centrifugado: "500 rpm",
    centrifugado: "Si",
    centrifugado_autoequilibrado: "No",
    dimensiones: "Alto: 89cm Prof.: 54cm Ancho: 54cm",
    peso: "33.6 kg",
    cantidad_programas: "15",
    tipo_lavarropas: "Automatico",
    niveles_temperatura: "Fría, Tibia, Caliente",
    filtro: "Si",
    tambor: "1, Polycron",
    display: "Si",
    tipo_bloqueo: "Bloqueo de Puerta",
    otro: "Lavado Rapido, Funcion Antiarrugas",
  },
  {
    id: 38,
    img: "https://i.ibb.co/HqYQFrS/Secarropas-Koh-i-Noor-Negro-N-655-2-5-5-KG.jpg",
    title: "Secarropas Koh i Noor Negro N-655-2 5.5KG",
    price: "$00,00",
    category: "lavarropas",
    marca: "KOH I NOOR",
    modelo: "N-655",
    capacidad: "5.5 kg",
    tambor: "1, de Acero Inoxidable",
    secado: "Centrifugo",
    carga: "Superior",
    dimensiones: "Alto: 63.5cm Diametro: 34.3cm",
    velocidad_centrifugado: "2800 rpm",
    sistema_traba: "Maxima Seguridad TBS",
    tapa: "Abre sola cuando deja de Girar el Tambor",
    otro: "Manija para Transportar, Patas de muy buena sujecion",
    telas: "Algodon, Lana, Toalla, Jean, Lycra, Sintetico, Polyester, etc.",
  },
  {
    id: 39,
    img: "https://i.ibb.co/TLJq7Qc/Secarropas-Koh-i-Noor-Acero-A-665-2-6-5-KG.jpg",
    title: "Secarropas Koh i Noor Acero A-665-2 6.5KG",
    price: "$00,00",
    category: "lavarropas",
    marca: "KOH I NOOR",
    modelo: "A-665",
    capacidad: "6.5 Kg",
    tambor: "1, de Acero Inoxidable",
    carga: "Superior",
    dimensiones: "Alto: 69.5cm Prof.: 34.3cm Ancho: 34.3cm",
    velocidad_centrifugado: "2800 rpm",
    sistema_traba: "Maxima Seguridad TBS",
    tapa: "Abre sola cuando deja de Girar el Tambor",
    otro: "Manija para Transportar, Patas de muy buena sujecion",
    telas: "Algodon, Lana, Toalla, Jean, Lycra, Sintetico, Polyester, etc.",
  },
  {
    id: 40,
    img: "https://i.ibb.co/7zRQrsD/Cocina-Vitta-Bella-Bianca-Multigas.jpg",
    title: "Cocina Vitta Bella Bianca Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Bianca",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 41,
    img: "https://i.ibb.co/ChMQmbG/Cocina-Vitta-Bella-Nera-Multigas.jpg",
    title: "Cocina Vitta Bella Nera Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Nera",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 42,
    img: "https://i.ibb.co/pxFrvGj/Cocina-Vitta-Bella-Acero-Multigas.jpg",
    title: "Cocina Vitta Bella Acero Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Acero",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 43,
    img: "https://i.ibb.co/0y57wXV/Cocina-Vitta-Semi-Industrial-Bella-Chef.jpg",
    title: "Cocina Vitta Semi Industrial Bella Chef",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Chef - Semi Industrial",
    dimensiones: "Alto 86cm, Prof.: 58cm Ancho: 55cm",
    piso: "Ladrillo Refractario",
    puertas: "Vidrio Templado",
    estilo: "Rejas de Fundicion, Acero Inoxidable Esmerilado con Pirometro en Puerta",
  },
  {
    id: 44,
    img: "https://i.ibb.co/Trp8wGz/Cocina-Electrolux-Doble-Horno-Elec-Gas.jpg",
    title: "Cocina Electrolux Doble Horno Elec-Gas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "ELECTROLUX",
    modelo: "56DXQ",
    grill: "No",
    temporizador: "Si",
    comando_tactil: "No",
    horno_autolimpiante: "No",
    cantidad_hornallas: "4",
    peso: "46.5 kg",
    dimensiones: "Alto: 146.5cm Ancho: 56cm Prof.: 107.4cm",
    alimentacion: "Gas y Electrica",
    industrial: "No",
    capacidad_horno: "106.5 Litros",
    horno_doble: "Si",
    parrillas: "3",
    tipo_energia: "A",
    tapa: "Si",
  },
  {
    id: 45,
    img: "https://i.ibb.co/BgH66Jw/Cocina-Industrial-Motta-Pro-Pv-520-G-N.jpg",
    title: "Cocina Industrial Motta Pro Pv 520 G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "MOTTA",
    modelo: "MO520PVN",
    dimensiones: "Alto: 86cm Prof.: 55cm Ancho: 53cm",
    cantidad_hornallas: "4",
    puertas: "Vidrio Color Negro",
    grill: "Si, Inferior",
    otro: "Rejas de Fundicion, Exterior de Acero Inox. interior Enlozado",
    parrillas: "2",
  },
  {
    id: 46,
    img: "https://i.ibb.co/yhf9DCf/Cocina-Industrial-Motta-Pro-600-Negra-G-N.jpg",
    title: "Cocina Industrial Motta Pro 600 Negra G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "MOTTA",
    modelo: "Pro 600 Negra G-N",
    dimensiones: "Alto: 86cm Prof.: 64cm Ancho: 59cm",
    cantidad_hornallas: "4",
    puertas: "Vidrio Color Negro",
    grill: "Si, Inferior",
    otro: "Rejas de Fundicion, Exterior de Acero Inox. interior Enlozado",
    parrillas: "2",
  },
  {
    id: 47,
    img: "https://i.ibb.co/5jXGPdX/Cocina-Industrial-Compacta-El-Gauchito-G-N.jpg",
    title: "Cocina Industrial Compacta El Gauchito G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "EL GAUCHITO",
    modelo: "550",
    industrial: "Si",
    cantidad_hornallas: "4",
    valvula_seguridad: "Si",
    tapa: "No",
    puerta_horno: "Ciega",
    horno_doble: "No",
    temporizador: "No",
  },
  {
    id: 48,
    img: "https://i.ibb.co/5cMQKMT/Horno-Electrico-Vitta-Forno-blanco-45l-c-Anafe.jpg",
    title: "Horno Electrico Vitta Forno blanco 45l c-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno Bianco",
    capacidad_horno: "45 Litros",
    potencia: "1600 W",
    dimensiones: "Alto: 35cm, Prof.: 38cm, Ancho: 54cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 49,
    img: "https://i.ibb.co/qYT4vS3/Horno-Vitta-Electrico-DW-5094-CA-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico DW-5094CA 55L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno NERO",
    capacidad_horno: "55 Litros",
    potencia: "2000 W",
    dimensiones: "Alto: 37cm, Prof.: 42cm, Ancho: 56cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
    otro: "Pizza Bump",
  },
  {
    id: 50,
    img: "https://i.ibb.co/qYT4vS3/Horno-Vitta-Electrico-DW-5094-CA-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico DW-7004CA 70L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno NERO",
    capacidad_horno: "70 Litros",
    potencia: "2080 W",
    dimensiones: "Alto: 39cm, Prof.: 46cm, Ancho: 58cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
    otro: "Pizza Bump",
  },
  {
    id: 51,
    img: "https://i.ibb.co/LxQW8jG/Horno-Vitta-Electrico-Forno-Rosso-45-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico Forno Rosso 45L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno ROSSO",
    capacidad_horno: "45 Litros",
    potencia: "1600 W",
    dimensiones: "Alto: 35cm, Prof.: 38cm, Ancho: 54cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 52,
    img: "https://i.ibb.co/8BdkZhH/Horno-Vitta-Electrico-Forno-Rosso-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico Forno Rosso 55L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno ROSSO",
    capacidad_horno: "55 Litros",
    potencia: "2000 W",
    dimensiones: "Alto: 37cm, Prof.: 42cm, Ancho: 56cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 53,
    img: "https://i.ibb.co/MnM0KvS/Horno-Vitta-Electrico-40l-VIT-HE4000012000-RC-1.jpg",
    title: "Horno Vitta Electrico 40l-50l-65l",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "HE4000- HE5000- HE6500",
    capacidad: "40 Litros, 50 Litros & 65 Litros",
    funcion: "Espiedo",
    anafe: "Doble",
    potencia:"2000W",
    niveles_temperatura:"250 Cº",
    otro: "Incluye Bandeja y 2 Pinzas",
  },
  {
    id: 54,
    img: "https://i.ibb.co/zSkxGB2/Microondas-Samsung-Blanco-20lts-ME731-KKD.jpg",
    title: "Microondas Samsung Blanco 20lts ME731KKD",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "SAMSUNG",
    modelo: "ME731K-KD",
    grill: "No",
    descongelado_automatico: "Si, 4 Programas de Descongelamiento",
    capacidad: "20 Litros",
    temporizador: "Sí",
    display: "Si, Digital",
    potencia: "800 W",
    niveles_potencia: "6",
    descongelamiento_rapido: "Si",
  },
  {
    id: 55,
    img: "https://i.ibb.co/tKLZrkV/Microondas-Samsung-Negro-23lts-MG23-F3-K3-TAK.jpg",
    title: "Microondas Samsung Negro 23lts MG23F3K3TAK",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "SAMSUNG",
    modelo: "MG23F3K3TA",
    grill: "Sí",
    descongelado_automatico: "Si, 4 Programas de Descongelamiento",
    capacidad: "23 Litros",
    temporizador: "No",
    display: "Si, Digital",
    potencia: "800 W",
    potencia_grill: "1050 W",
    niveles_potencia: "6",
    descongelamiento_rapido: "Si",
    sleep: "Si",
    detail: "El horno microondas Samsung MG23 cuenta con 20 modos de cocción preestablecidos, con los que vas a poder preparar comida fresca en minutos. Además, presenta simples funciones de uso, como descongelamiento, timer y traba para niños que bloquea el teclado, para evitar accidentes. Y el ajuste de Modo Eco ofrece un menor consumo de energía en espera, para ahorrar más. El microondas Samsung MG23 presenta un elegante diseño con el frente en vidrio negro, encerrado en un fino patrón a tono y manija plateada. Su interior de cerámica lisa es antibacteriano y resistente a los rayones. Además, es fácil de limpiar y no se decolora ni se raya con el tiempo.",
  },
  {
    id: 56,
    img: "https://i.ibb.co/9H3MMrG/Microondas-Samsung-Silver-23lts-MG23-F3-K3-TA.jpg",
    title: "Microondas Samsung Silver 23lts MG23F3K3TA",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "SAMSUNG",
    detail: "No pierdas tiempo en la cocina. En simples pasos, podés disfrutar de tus comidas favoritas gracias a la tecnología y evolución de Samsung. El mismo cuenta con recetas preprogramadas para tu comodidad. Cocina fácilmente todo, desde arroz integral hasta pechuga de pollo deshuesada y filetes de salmón a la parrilla, con la garantía de que el resultado será comida fresca y sabrosa. Variedad de funciones y programas. Su función de grill permite dorar los alimentos para que queden crocantes, ideal para pizzas, empanadas y tartas. Para destacar, este microondas cuenta con 6 diferentes niveles de cocción y programas. Disfrutá todas tus comidas con mínimo esfuerzo y máximo sabor. Diseño innovador y accesorios. La libertad es absoluta, ya que podrás llevarlo adonde desees cuando te mudes. Su display te permitirá ser más preciso al momento de seleccionar el tipo de comida, configurar el tiempo y la función para cocinar. Además, presenta un excelente sistema de seguridad con traba especial para las personas más pequeñas de la familia. Capacidad y eficiencia. Con un volumen de 23 litros vas a poder disfrutar comidas para compartir con tus amistades y familiares. Ofrece una potencia máxima de 800 watts que se puede regular en diferentes niveles según el tipo de alimento, por ejemplo, para evitar que se resequen algunos platos más delicados como la pasta. Con su fácil uso, podrás seleccionar y programar de manera práctica. Lo hace todo por vos. Solo debes colocar el peso de los alimentos y el microondas automáticamente programará el tiempo necesario para que el mismo se descongele.",
  },
  {
    id: 57,
    img: "https://i.ibb.co/T1RSnZW/Microondas-Samsung-Silver-28-lts-MG28-F3-K3-T.jpg",
    title: "Microondas Samsung Silver 28 lts MG28F3K3T",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "SAMSUNG",
    detail: "Diseño innovador y accesorios. La libertad es absoluta, ya que podrás llevarlo adonde desees cuando te mudes. Su display te permitirá ser más preciso al momento de seleccionar el tipo de comida, configurar el tiempo y la función para cocinar. Además, presenta un excelente sistema de seguridad con traba especial para las personas más pequeñas de la familia. Capacidad y eficiencia. Con un volumen de 28 litros vas a poder disfrutar comidas para compartir con tus amistades y familiares. Ofrece una potencia máxima de 900 watts que se puede regular en diferentes niveles según el tipo de alimento, por ejemplo, para evitar que se resequen algunos platos más delicados como la pasta. Con su fácil uso, podrás seleccionar y programar de manera práctica.",
  },
  {
    id: 58,
    img: "https://i.ibb.co/RBdWT64/Licuadora-3-en-1-Star-Trak-Acero-Vaso-de-Vidrio.jpg",
    title: "Licuadora 3 en 1 Star Trak Acero Vaso de Vidrio",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "STAR TRAK",
    detail: "Licuadora STAR TRAK Jarra de Vidrio con 1000W Super Potentes. Pica Hielo, especial para Bartender, Incluye Accesorio de Molinillo de Cafe / Semillas. Practica Botonera de 5 velocidades Graduales con Luz Led & TURBO para una mejor Experiencia.",
  },
  {
    id: 59,
    img: "https://i.ibb.co/1Jw7vVG/Licuadora-Westinghouse-BL0800-LA0-Negra.jpg",
    title: "Licuadora Westinghouse BL0800LA0 Negra",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "WESTINGHOUSE",
    detail: "Un electrodoméstico infaltable en tu casa. La licuadora Westinghouse WH-BL0800LA0 te va a ayudar a obtener resultados increíbles en todo lo que prepares, ya sea que quieras disfrutar de una bebida bien fría, de salsas y sopas, o de postres deliciosos. ¡Tenela siempre a mano!. Práctica y segura. Su cierre de seguridad impide accidentes por descuidos y preserva la limpieza de tu cocina al evitar derrames. Todo lo que más te gusta. Es apta para moler hielo en segundos y preparar smoothies refrescantes en los días de calor. Además, podés hacer tus propios tragos de coctelería en casa sin necesidad de ir a un bar. Ahora el bartender ¡sos vos!",
  },
  {
    id: 60,
    img: "https://i.ibb.co/PD8DDT8/Licuadora-Yelmo-700w-1-5-Vaso-de-Vidrio-LC-1010.jpg",
    title: "Licuadora Yelmo 700w 1.5 Vaso de Vidrio LC-1010",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "YELMO",
    detail: "Un electrodoméstico infaltable en tu casa. La licuadora Yelmo LC-1010 te va a ayudar a obtener resultados increíbles en todo lo que prepares, ya sea que quieras disfrutar de una bebida bien fría, de salsas y sopas, o de postres deliciosos. ¡Tenela siempre a mano!. Práctica y segura. Su función pulsar te permite poner en marcha el producto de forma intermitente según lo necesites o de acuerdo al contenido de la jarra. Todo lo que más te gusta. Es apta para moler hielo en segundos y preparar smoothies refrescantes en los días de calor. Además, podés hacer tus propios tragos de coctelería en casa sin necesidad de ir a un bar. Ahora el bartender ¡sos vos!",
  },
  {
    id: 61,
    img: "https://i.ibb.co/sscw7VH/Licuadora-Liliana-Delux-Jarra-AL180.jpg",
    title: "Licuadora Liliana Delux Jarra AL180",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "LILIANA",
    detail: "Con la licuadora portátil Liliana AL180 prepará tus licuados donde sea que estés, y tendrás colaciones o meriendas nutritivas, llenas de sabor en cualquier momento del día. Práctica y segura. La función turbo hace que los ingredientes se mezclen con mayor rapidez y de manera homogénea para lograr preparaciones con texturas insuperables. Todo lo que más te gusta. Es apta para moler hielo en segundos y preparar smoothies refrescantes en los días de calor. Además, podés hacer tus propios tragos de coctelería en casa sin necesidad de ir a un bar. Ahora el bartender ¡sos vos!. Siempre limpia. Su cuchilla removible asegura que el lavado sea impecable y evita la acumulación de residuos que podrían perjudicar el sabor de los alimentos.",
  },
  {
    id: 62,
    img: "https://i.ibb.co/jbYbm67/Juguera-Electrica-Liliana-Nutrijug-350-ML-AAJ950.jpg",
    title: "Juguera Electrica Liliana Nutrijug 350 ML AAJ950",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "LILIANA",
    detail: "¿Hay algo mejor que un jugo fresco en cualquier momento del día? Tus frutas y verduras preferidas aportan las vitaminas y minerales que tu cuerpo necesita, y con la juguera Liliana podrás hacerlo muy fácil. Sacale jugo a tu día. Para un mayor control en la elaboración de tus bebidas, tendrás la posibilidad de seleccionar entre las 2 velocidades que este electrodoméstico ofrece. Su recolector de pulpa te permitirá mantenerla separada y extraer todo el líquido. Así vas a aprovechar al máximo las frutas y verduras que elijas.",
  },
  {
    id: 63,
    img: "https://i.ibb.co/MBKBXJL/Multiprocesadora-Liliana-Simplix-700-W-AAM700.jpg",
    title: "Multiprocesadora Liliana Simplix 700W AAM700",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "LILIANA",
    detail: "Marca argentina y con presencia en todo el país, es símbolo de innovación, ofreciendo productos adaptados al estilo de vida actual desde hace ya más de 60 años de trayectoria. Esta multiprocesadora Liliana se convertirá en tu aliada imprescindible a la hora de preparar tus comidas. Como un chef profesional. ¡Abrí el libro de recetas y poné manos a la obra! Lograrás tener resueltos tus almuerzos y cenas en pocos pasos y sin limitaciones. Batí y amasá los ingredientes de tus tortas y postres sin tener que ensuciarte las manos. Todo en uno. Por otro lado, se complementa con sus accesorios ya que incluye: amasador, batidor - emulsionador, cuchilla picadora, disco porta accesorios, eje porta accesorios, rallador, rebanador, tapa embutidor. Son fáciles de utilizar e intercambiar ya que encajan perfectamente gracias a su diseño.",
  },
  {
    id: 64,
    img: "https://i.ibb.co/wpBRg6t/Procesadora-B-D-FP1002-J-AR-750w-c-Vaso-licuadora.jpg",
    title: "Procesadora B+D FP1002J-AR 750w c-Vaso licuadora",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "BLACK & DECKER",
    detail: "Multiprocesadora Black + Decker Fp1002J-ar 750 Watts. 3 Velocidades y jarra licuadora. Todo en uno. ¡Abrí el libro de recetas y poné manos a la obra! Lograrás tener resueltos tus almuerzos y cenas en pocos pasos y sin limitaciones. Amasá la mezcla de tus galletitas o panes caseros y viví la experiencia de tener una panadería en casa. Prepará diversas salsas dulces o saladas y dale el toque final a todas tus creaciones. ¡Obtenga una amplia variedad de alimentos, como bebidas de frutas, salsas, sopas y hasta la comida del bebé!",
  },
  {
    id: 65,
    img: "https://i.ibb.co/48CSLB2/Batidora-Planetaria-Eurocook-Taurus-EC-BP1509-B.jpg",
    title: "Batidora Planetaria Eurocook Taurus EC-BP1509B",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "EUROCOOK",
    detail: "Esta batidora industrial eurocook EC-BP1509B es perfecta para preparar grandes cantidades de mezclas en pocos minutos. Se destaca por su potencia y capacidad de procesar ingredientes. Te permitirá acelerar la producción y aumentar la eficiencia del trabajo, ¡más preparaciones en menos tiempo!",
  },
  {
    id: 66,
    img: "https://i.ibb.co/7bPBRJQ/Batidora-Planetaria-Yelmo-Amarilla-8-Vel-BB-1103-A.jpg",
    title: "Batidora Planetaria Yelmo Amarilla 8 Vel BB-1103A",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "YELMO",
    detail: "Esta batidora industrial Yelmo BB-1103 es perfecta para preparar grandes cantidades de mezclas en pocos minutos. Se destaca por su potencia y capacidad de procesar ingredientes. Te permitirá acelerar la producción y aumentar la eficiencia del trabajo, ¡más preparaciones en menos tiempo!. La batidora Yelmo BB-1103 cuenta con soporte y bowl integrados que mantienen fijo el producto y facilitan su uso, ya que no es necesario estar pendiente de su funcionamiento. Ahorrá tiempo y ganá en resultados deliciosos. Además incluye 1 batidor de gancho, 1 batidor elíptico, 1 batidor plano recubierto, 1 tapa anti salpicaduras.",
  },
  {
    id: 67,
    img: "https://i.ibb.co/whp1ZkP/Batidora-Planetaria-Westing-House-Blanca-Gris.jpg",
    title: "Batidora Planetaria WestingHouse Blanca-Gris",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "WESTINGHOUSE",
    detail: "La batidora planetaria hace unos movimientos rotatorios por todos los rincones del recipiente. Este movimiento, llamado orbital, ayuda a que la masa se reparta y se mezcle de forma mucho más homogénea. Gracias a su potencia te permite preparar fácilmente tartas, galletas, magdalenas, puré de papas y muchas cosas más. Su bowl de acero inoxidable será duradero y además fácil de limpiar. Además cuenta con varias velocidades y 3 tipos de ganchos batidores.",
  },
  {
    id: 68,
    img: "https://i.ibb.co/P9Z0rLP/Horno-de-Pan-Liliana-Full-Bread-850-W-AFP910.jpg",
    title: "Horno de Pan Liliana Full Bread 850W AFP910",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "LILIANA",
    detail: "Nada mejor que disfrutar del irresistible aroma a pan recién hecho por las mañanas y en tu casa. Con el horno de pan Liliana podrás tener los mejores desayunos caseros todos los días. Lográ el punto justo. Elaborá deliciosas preparaciones de forma simple con sus 12 programas preestablecidos que controlan la temperatura y el tiempo para que obtengas los mejores resultados. Seleccioná cualquiera de las 4 intensidades de tostado para disfrutar del pan como más te guste; podrás elegir entre una corteza más clara u oscura, según tus preferencias. Tus recetas más prácticas. Con su temporizador, podrás dejar programada la preparación la noche anterior, y disfrutarás del pan listo cuando te despiertes o en cualquier momento del día. A través de su ventana verás el funcionamiento interno de la máquina mientras amasa, mezcla y hornea. Es ideal para ver el progreso y controlar que todo el proceso se esté haciendo correctamente. Potenciá su uso. Conocé todas las funciones que tiene disponible el horno de pan: mezcla, amasa, leuda, hornea, hace mermelada. Vas a poder preparar diferentes variedades de pan, masas para pastas y demás panificaciones todo en un mismo electrodoméstico para disfrutar en compañía.",
  },
  {
    id: 69,
    img: "https://i.ibb.co/26wHs1q/Freidora-Electrica-de-Aire-Black-Decker-HFD1010-B.jpg",
    title: "Freidora Electrica de Aire Black Decker HFD1010B",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "BLACK & DECKER",
    detail: "Cociná saludable con la Freidora de Aire Digital BLACK+DECKER®. Es perfecta para freír y hornear tus comidas favoritas en poco tiempo ya que cuenta con 1000 Watts de potencia. Puedes disfrutar tus deliciosos alimentos favoritos sin grasa y con el mismo sabor ya que sus 7 funciones de cocción automática brinda facilidad a la hora de cocinar. Usa 99.5% menos aceite y sigue disfrutando la textura crujiente y el sabor sin grasa adicional. Su pantalla táctil digital es fácil de usar y la cesta de freír puede contener hasta 2.1 litros de alimentos, haciendo fácil freír meriendas o un plato principal para varias personas. Con esta revolucionaria manera de cocinar, puedes disfrutar deliciosos alimentos fritos sin grasa y con el mismo sabor. Los ventiladores de convección de alta potencia hacen que el aire circule rápidamente alrededor de la comida creando un sabor frito crujiente.",
  },
  {
    id: 70,
    img: "https://i.ibb.co/PDLTzx8/Juego-de-5-Piezas-Aluminio-Teflon-Mta-Safira-Negra.jpg",
    title: "Juego de 5 Piezas Aluminio Teflon Mta Safira Negra",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "MTA SAFIRA",
    detail: "Confeccionado en aluminio de 1.2 mm, con revestimiento interno y externo de antiadherente Superflon. Sus 5 capas exclusivas de antiadherente evitan que los alimentos se peguen a la superficie. Su diseño funcional hace de estas piezas un set imprescindible para quienes buscan practicidad en la preparación de alimentos. Además, cuenta con tapas de vidrio templado con salida de vapor que facilitan la cocción permitiendo visualizar los alimentos. Sus mangos y asas confeccionadas en bakelita atérmica reducen la propagación del calor. Pueden utilizarse en cocinas a gas, eléctricas y vitrocerámicas y son aptas para lavavajillas.",
  },
  {
    id: 71,
    img: "https://i.ibb.co/8409FBM/Balanza-Comercial-Kretz-Novel-Eco-2-30kg-AUN30-P.jpg",
    title: "Balanza Comercial Kretz Novel Eco 2 30kg AUN30P",
    price: "$00,00",
    category: "equipamiento",
    marca: "KRETZ",
    detail: "Este instrumento brinda la precisión, calidad y tecnología que necesitás en tu negocio para pesar con exactitud. Además, cuenta con una gran variedad de funciones que permiten trabajar con comodidad. Kretz se posiciona en el mercado internacional por diseñar soluciones tecnológicas innovadoras para tu negocio. Ofrece productos de calidad y alta eficiencia, y brinda un excelente servicio. Con la balanza Novel Eco 2 todo se vuelve mucho más fácil. No solo determina el peso exacto de los productos, sino que también agiliza las tareas de tu negocio y te ayuda a reducir los tiempos de espera de tus clientes. Display digital. Olvidate de pesos inexactos, la mayor ventaja de tener una balanza con pantalla digital es que te muestra de manera clara y precisa tu pesaje. La practicidad de la tecla Tara. Esta tecla convierte la balanza en una herramienta de trabajo práctica, que posibilita restar el peso del recipiente que contiene el producto y alcanzar la medida exacta. Menos errores con los códigos PLU. Con los códigos PLU que dispone este equipo, vas a obtener múltiples beneficios. Por un lado, vas a lograr simplificar las operaciones de la caja registradora y del control de inventario. Pero también, vas a minimizar errores y garantizar que quienes compren paguen el precio correcto.",
  },
  {
    id: 72,
    img: "https://i.ibb.co/3vVF61f/Balanza-Comercial-Kretz-Etiquetadora-Report-30kg.jpg",
    title: "Balanza Comercial Kretz Etiquetadora Report 30kg",
    price: "$00,00",
    category: "equipamiento",
    marca: "KRETZ",
    detail: "Este instrumento brinda la precisión, calidad y tecnología que necesitás en tu negocio para pesar con exactitud. Además, cuenta con una gran variedad de funciones que permiten trabajar con comodidad. Kretz se posiciona en el mercado internacional por diseñar soluciones tecnológicas innovadoras para tu negocio. Ofrece productos de calidad y alta eficiencia, y brinda un excelente servicio. Con la balanza Report NX Bluetooth + USB todo se vuelve mucho más fácil. No solo determina el peso exacto de los productos, sino que también agiliza las tareas de tu negocio y te ayuda a reducir los tiempos de espera de tus clientes. Display digital. Olvidate de pesos inexactos, la mayor ventaja de tener una balanza con pantalla digital es que te muestra de manera clara y precisa tu pesaje. La practicidad de la tecla Tara. Esta tecla convierte la balanza en una herramienta de trabajo práctica, que posibilita restar el peso del recipiente que contiene el producto y alcanzar la medida exacta. Menos errores con los códigos PLU. Con los códigos PLU que dispone este equipo, vas a obtener múltiples beneficios. Por un lado, vas a lograr simplificar las operaciones de la caja registradora y del control de inventario. Pero también, vas a minimizar errores y garantizar que quienes compren paguen el precio correcto.",
  },
  {
    id: 73,
    img: "https://i.ibb.co/qC6xDr7/Balanza-Comercial-Kretz-Aura-Eco-30kg-AUI30-P.jpg",
    title: "Balanza Comercial Kretz Aura Eco 30kg AUI30P",
    price: "$00,00",
    category: "equipamiento",
    marca: "KRETZ",
    detail: "Con la balanza Aura Eco todo se va a volver mucho más fácil. No solo te va a permitir determinar el peso exacto de los productos que comercialices, sino que también vas poder agilizar las tareas de tu negocio y reducir los tiempos de espera de tus clientes. ¿No es genial?. La practicidad de la tecla Tara. Aunque es solo una tecla, convierte la balanza en una herramienta de trabajo práctica, que posibilita restar el peso del recipiente que contiene el producto y alcanzar la medida exacta. 8000 códigos PLU disponibles. Los códigos PLU te acercan múltiples beneficios. Por un lado, vas a lograr simplificar las operaciones de la caja registradora y del control de inventario. Pero también, vas a minimizar errores y garantizar que quienes compren paguen el precio correcto.",
  },
  {
    id: 74,
    img: "https://i.ibb.co/pzRwjfG/Aspiradora-Ultracomb-C-Bolsa-1600-W-AS4210.jpg",
    title: "Aspiradora Ultracomb C-Bolsa 1600W AS4210",
    price: "$00,00",
    category: "pequeños hogar",
    marca: "ULTRACOMB",
    detail: "Con su línea de limpieza, Ultracomb hace que disfrutes de tu casa al máximo. Nunca fue tan fácil y rápido dejarla como nueva. A prueba de alergias. El sistema de filtrado retiene la suciedad, logrando que el aire que sale del aparato esté totalmente puro y libre de las partículas que producen molestias respiratorias. Capacidad completa. Cuando su capacidad de almacenamiento esté completa, lo sabrás de inmediato a través de una luz o sonido indicador. Así no la sobrecargarás y evitarás roturas. Complementos. Esta aspiradora incluye los siguientes accesorios: boquilla multiuso, cepillo para pisos y alfombras, 2 tubos prolongadores, manguera, boquilla rinconera con cepillo.",
  },
  {
    id: 75,
    img: "https://i.ibb.co/F4h4rTy/Aspiradora-Ultracomb-S-Bolsa-1400-W-1-2-L-AS-4220.jpg",
    title: "Aspiradora Ultracomb S-Bolsa 1400W 1,2L AS-4220",
    price: "$00,00",
    category: "pequeños hogar",
    marca: "ULTRACOMB",
    detail: "Con su línea de limpieza, Ultracomb hace que disfrutes de tu casa al máximo. Nunca fue tan fácil y rápido dejarla como nueva. A prueba de alergias. El sistema de filtrado retiene la suciedad, logrando que el aire que sale del aparato esté totalmente puro y libre de las partículas que producen molestias respiratorias. Complementos. Esta aspiradora incluye los siguientes accesorios: boquilla multiuso, cepillo para pisos y alfombras.",
  },
  {
    id: 76,
    img: "https://i.ibb.co/QvPss7b/Aspiradora-Ultracomb-S-Bolsa-1800-W-2-5-L-AS-4224.jpg",
    title: "Aspiradora Ultracomb S-Bolsa 1800W 2,5L AS-4224",
    price: "$00,00",
    category: "pequeños hogar",
    marca: "ULTRACOMB",
    detail: "Con su línea de limpieza, Ultracomb hace que disfrutes de tu casa al máximo. Nunca fue tan fácil y rápido dejarla como nueva. A prueba de alergias. El sistema de filtrado retiene la suciedad, logrando que el aire que sale del aparato esté totalmente puro y libre de las partículas que producen molestias respiratorias. Complementos. Esta aspiradora incluye los siguientes accesorios: cepillo para pisos y alfombras, set de boquillas.",
  },
  {
    id: 77,
    img: "https://i.ibb.co/4d1cT4X/Aspiradora-Black-Decker-C-Bolsa-1800-W-VCBD1800.jpg",
    title: "Aspiradora Black & Decker C-Bolsa 1800W VCBD1800",
    price: "$00,00",
    category: "pequeños hogar",
    marca: "BLACK & DECKER",
    detail: "Aspira en pocas pasadas partículas de polvo pequeñas y grandes con la aspiradora Power Pro de BLACK+DECKER® que posee un depósito de 2 litros y filtro removible de fácil limpieza. Su potencia de 1800 watts y sistema ciclónico permite una succión continua y potente sin interrupciones. El cable retráctil facilita su almacenamiento. Incluye: cepillo 2 en 1 para pisos y alfombras, 2 tubos de extensión, manguera giratoria flexible, cepillo esquinero, bolsa de tela lavable.",
  },
  {
    id: 78,
    img: "https://i.ibb.co/9VLDjfB/Aspiradora-Samsung-VC20-CCNMARF-Red-Flame.jpg",
    title: "Aspiradora Samsung VC20CCNMARF Red Flame",
    price: "$00,00",
    category: "pequeños hogar",
    marca: "SAMSUNG",
    detail: "Tus días de limpieza serán más simples con esta aspiradora Samsung. Vas a poder deshacerte del polvo y de los residuos con rapidez y así dejar tus ambientes impecables. A prueba de alergias. El sistema de filtrado retiene la suciedad, logrando que el aire que sale del aparato esté totalmente puro y libre de las partículas que producen molestias respiratorias. Complementos. Esta aspiradora incluye los siguientes accesorios: manguera, cepillo para pisos y alfombras nb300, boquilla de cepillo, boquilla rinconera.",
  },
  {
    id: 79,
    img: "https://i.ibb.co/gz8csh6/Aspiradora-Ciclonica-Ultra-Comb-7-L-Gris-AS-4230.jpg",
    title: "Aspiradora Ciclonica UltraComb 7L Gris AS-4230",
    price: "$00,00",
    category: "pequeños hogar",
    marca: "ULTRACOMB",
    detail: " Con su línea de limpieza, Ultracomb hace que disfrutes de tu casa al máximo. Nunca fue tan fácil y rápido dejarla como nueva. A prueba de alergias. El sistema de filtrado retiene la suciedad, logrando que el aire que sale del aparato esté totalmente puro y libre de las partículas que producen molestias respiratorias.",
  },
  {
    id: 80,
    img: "https://i.ibb.co/44j6yP4/Termotanque-Gris-Electrico-Blanco-Gas-150-100-80-50-25-lts-Vitta.jpg",
    title: "Termotanque Gris Electrico-Blanco Gas 150-100-80-50-25 lts Vitta",
    price: "$00,00",
    category: "termotanques",
    marca: "VITTA",
    detail: "¡Que nada arruine tu momento bajo la ducha! ¿Sabías que con un termotanque podés tener varias canillas abiertas en simultáneo sin perder presión? Y podés variar la temperatura durante su uso. Son más grandes, seguros y requieren menor mantenimiento que un calefón. ¡No lo pienses tanto!. Máximo rendimiento. Al momento de sumar un termotanque eléctrico a tu casa, tené en cuenta la enorme ventaja que tiene: no emite monóxido de carbono. Cuidate y cuidá a quienes más querés. Usalo con confianza. Con su válvula de seguridad vas a evitar problemas de sobrepresión y proteger el funcionamiento del termotanque. Priorizá la seguridad y llevá lo mejor a tu hogar. La válvula de desagüe reduce la presión al abrir y expulsar el exceso de agua cuando la presión supere cierto nivel. Además, cuenta con aislación térmica, que permite conservar el calor durante más tiempo. Una vez que el agua llega a la temperatura deseada, deja de consumir energía, por lo que vas a ahorrar mucho más.",
  },
  {
    id: 81,
    img: "https://i.ibb.co/YRvLMRG/Termotanque-Electrico-Sherman-Pie-55-L.jpg",
    title: "Termotanque Electrico Sherman Colgante 55L & 85L",
    price: "$00,00",
    category: "termotanques",
    marca: "SHERMAN",
    detail: "CON AISLAMIENTO DE POLIURETANO ECOLÓGICO (2,5 veces más asilante que la lana de vidrio) que conserva más tiempo la temperatura del agua y ahorra más energía. MAYOR RECUPERACIÓN de litros de agua caliente por hora. APTO PARA BOMBA DE PRESION. MAS DURADEROS Unico con esmalteporcelanizado en el tanque interno. MAS SEGUROS Sensor de sobretemperatura",
  },
  {
    id: 82,
    img: "https://i.ibb.co/GcCckVp/Termotanque-Electrico-Sherman-Pie-85-L.jpg",
    title: "Termotanque Electrico Sherman Con Pie 55L & 85L",
    price: "$00,00",
    category: "termotanques",
    marca: "SHERMAN",
    detail: "Base de Apollo, nueva tecnologia ¡CON PIE! Cuenta con AISLAMIENTO de POLIURETANO ECOLÓGICO (2,5 veces más asilante que la lana de vidrio) que conserva más tiempo la temperatura del agua y ahorra más energía. MAYOR RECUPERACIÓN de litros de agua caliente por hora. APTO PARA BOMBA DE PRESION. MAS DURADEROS Unico con esmalteporcelanizado en el tanque interno. MAS SEGUROS Sensor de sobretemperatura",
  },
  {
    id: 83,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 84,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 85,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 86,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 87,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 88,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 89,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 90,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 91,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 92,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 93,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 94,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 95,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 96,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 97,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 98,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 99,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 100,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 101,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 102,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 103,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 104,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 105,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 106,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 107,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 108,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 109,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 110,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
  {
    id: 111,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",
  },
];


/* export const columns = [{
   name: "Marca",
   selector: "marca",
   soportable: true
},{
  name: "codigo",
  selector: "codigo",
  soportable: true
},
{
  name: "Conectividad",
  selector: "Conectividad",
  soportable: true
},
{
  name: "Marca",
  selector: "marca",
  soportable: true
},

] */
export default function getItems() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(data);
    }, 2000);
  });
}

export function getItemsSingle(idItem) {
  return new Promise((resolve, reject) => {
    let itemFind = data.find((item) => {

      return item.id === parseInt(idItem);
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}

export function getItemsByCategory(cat) {
  return new Promise((resolve, reject) => {
    let itemFind = data.filter((item) => {
      return item.category === cat;
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}


