const data = [
  {
    id: 1,
    img: "https://i.ibb.co/0QbcYBS/Aire-acondicionado-Split-Kanji-2600w-f-c-26fkht81.jpg",
    title: "Aire Acondicionado Split KANJI 2600w FC",
    price: "$00.00",
    category: "aire",
    marca: "KANJI",
    modelo: "26FKHT81",
    deflectoresmoviles: "Sí",
    frigorias: "2240",
    display: "No",
    timer: "Sí",
    automatico: "Si",
    sleep: "Sí",
    ventilacion: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    contro: "Sí",
    inverter: "No",
    gas: "R-410a",
  },
  {
    id: 2,
    img: "https://i.ibb.co/pKCPbxc/aire-acondicionado-split-hitachi-2600w-fc.jpg",
    title: "Aire Acondicionado Split HITACHI 2600w FC",
    price: "$00,00",
    category: "aire",
    marca: "HITACHI",
    tipo_equipo: "Split",
    frio_calor: "Sí",
    frigorias: "2499",
    gas: "R410A",
    tipo_energia: "A",
    automático: "Sí",
    deshumificación: "Sí",
    sleep: "Sí",
    medidasSplit: "27,5cm Alto - 85cm Ancho - 32cm Prof.",
    peso: "11 kg",
    medidasMotor: "54,5cm Alto - 70cm Ancho - 30cm Prof.",
    pesoMotor: "27 kg",
    control: "Sí",
  },

  {
    id: 3,
    img: "https://i.ibb.co/g9mKHqb/aire-acondicionado-split-kanji-3200w-fc.jpg",
    title: "Aire acondicionado Split KANJI 3200w FC",
    price: "$00,00",
    category: "imagen",
    marca: "KANJI",
    display: "No",
    deflectores_moviles: "Sí",
    frigorias: "2760",
    timer: "Sí",
    automatico: "Sí",
    sleep: "Sí",
    ventilación: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    control: "Sí",
    inverter: "No",
    gas: "R-410a",
  },
  {
    id: 4,
    img: "https://i.ibb.co/r67MbZ3/aire-acondicionado-inverter-greenstay-fc-3500.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 3500w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "3010",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
  },
  {
    id: 5,
    img: "https://i.ibb.co/HHG7r1D/aire-acondicionado-inverter-greenstay-fc-6900.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 6900w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "5934",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
  },
  {
    id: 6,
    img: "https://i.ibb.co/TLkWf51/ventilador-vitta-18pulgadas-3-en-1-90w.jpg",
    title: "Ventilador VITTA 18'' 3 en 1 90w",
    price: "$00,00",
    category: "ventilacion",
    marca: "VITTA",
    dimensiones: "46cm",
    tipo_ventilador: "Mesa, Pared, Pie",
    potencia: "90 w",
    velocidades: "3",
    aspas: "Metal",
    cantidad_aspas: "3",
  },
  {
    id: 7,
    img: "https://i.ibb.co/7V2dS40/ventilador-industrial-vitta-30-Pulgadas-2-en-1.jpg",
    title: "Ventilador Industrial Vitta 30'' 2 en 1",
    price: "$00,00",
    category: "ventilacion",
    marca: "VITTA",
    tipo_ventilador: "Pared, Pie",
    cantidad_aspas: "3",
    velocidades: "3",
    altura: "1,4 metros",
    potencia: "180W",
    aspas: "Plásticas",
  },

  {
    id: 8,
    img: "https://i.ibb.co/N6LrtJg/Ventilador-18-Pulgadas-3-en-1-STAR-TRAK.jpg",
    title: "Ventilador 18'' 3 en 1 STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Metal",
    potencia: "90W",
  },
  {
    id: 9,
    img: "https://i.ibb.co/MgJGJFf/Ventilador-Pie-14-Pulgadas-Base-Pesada-STAR-TRAK.jpghttps://picsum.photos/200/300?random=9",
    title: "Ventilador Pie 14'' Base Pesada STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos"
  },
  {
    id: 10,
    img: "https://i.ibb.co/WBR7xrp/Ventilador-Pie-14-Pulgadas-STAR-TRAK-Multi.jpg",
    title: "Ventilador Pie 14'' STAR TRAK Multi",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos",
  },
  {
    id: 11,
    img: "https://i.ibb.co/kcJYp06/Ventilador-14-Pulgadas-STAR-TRAK.jpg",
    title: "Ventilador 20'' STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,70 Metros",
    potencia: "120W",
    otro: "Repele Mosquitos",
  },
  {
    id: 12,
    img: "https://i.ibb.co/bdQqNYr/Climatizador-Philco-Portatil-7-L.jpg",
    title: "Climatizador Philco Portatil 7L",
    price: "$00,00",
    category: "calefaccion",
    marca: "PHILCO",
    velocidades: "3",
    tipo_equipo: "Oscilación",
    otro: "No requiere instalación",
    flujo_aire: "600 m3/h",
    cantidad_agua: "7 Lts (5 Lts con los cubos de hielo reutilizables)",
    detalles: "Indicador de nivel de agua",
    timer: "No",
    peso: "6,6 kgs",
    dimesion: "Alto: 70 cm Ancho: 28 cm Prof: 26,5 cm",
  },
  {
    id: 13,
    img: "https://i.ibb.co/B2h9Vv3/Climatizador-Kanji-LRG04-11-CR-Frio-Calor.jpg",
    title: "Climatizador Kanji LRG04-11CR Frio Calor",
    price: "$00,00",
    category: "calefaccion",
    marca: "KANJI",
    velocidades: "3",
    frio_calor: "Si",
    control: "Si",
    cantidad_agua: "8 Litros",
    dimensiones: "Alto 70 cm Ancho 37 cm Prof: 29 cm",
  },
  {
    id: 14,
    img: "https://i.ibb.co/nL5qRNX/Heladera-Briket-322-L-BK2-F-1610-Blanca-Gris-Negro.jpg",
    title: "Heladera Briket 322L BK2F 1610 Blanca-Gris-Negro",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "BK2F 1610",
    color: "Blanco, Gris o Negro",
    freezer: "Superior",
    estantes_freezer: "1",
    dimensiones: "Ancho: 66cm Altura: 164cm Prof: 682cm",
    estantes_heladera: "3",
    dispenser_agua: "No",
    dispenser_hielo: "No",
    luz_interior: "Si",
    cantidad_puertas: "2",
    inverter: "No",
    tipo_energia: "A+",
    capacidad: "322 Litros",
    congelador: "No",
    vegetales: "Si",
    porta_botellas: "No",
    porta_latas: "No",
    porta_huevos: "Si",
  },
  {
    id: 15,
    img: "https://i.ibb.co/F0wyRpN/Heladera-Briket-476-L-BK2-F-2121-Gris.jpg",
    title: "Heladera Briket 476L BK2F 2121 Gris",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    Modelo: "BK2F 2121",
    dimensiones: "Ancho: 66cm x Prof: 75cm x Alto: 189 cm",
    inverter: "No",
    tipo_energia: "A+",
    deshielo: "Manual",
    freezer: "Superior",
    luz_interior: "Sí",
    puertas: "2",
  },
  {
    id: 16,
    img: "https://i.ibb.co/1X2pcjr/Heladera-SIAM-Top-Mount-370l-C-Disp-inox.jpg",
    title: "Heladera SIAM Top Mount 370l C-Disp inox",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "SIAM",
    modelo: "HSI-NT30XD",
    estilo: "Acero inoxidable",
    freezer: "Superior",
    estantes_freezer: "1",
    fabrica_hielo: "Si",
    peso: "68 Kg",
    dimensiones: "Ancho: 69.6cm Prof: 68.5cm Alto: 171.2cm",
    estantes_heladera: "3",
    dispenser_agua: "Si",
    dispenser_hielo: "Si",
    luz_interior: "Si",
    inverter: "Si",
    deshielo: "No Frost",
    tipo_energia: "A",
    capacidad: "404 Litros",
    niveles_temperatura: "6",
    porta_vegetales: "Si",
    cantidad_puertas: "2",
    display: "No",
  },
  {
    id: 17,
    img: "https://i.ibb.co/d4rRygF/Heladera-Samsung-Inox-321-L-con-display-RT32-K5930-SL.jpg",
    title: "Heladera Samsung Inox 321L con display RT32K5930SL",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "SAMSUNG",
    modelo: "Rt32k5930sl",
    inverter: "Si",
    dimensiones: "Ancho: 60cm, Prof.: 67.2cm Alto: 171.5cm",
    luz_interior: "Si",
    tipo_energia: "A+",
    enfriamiento: "No Frost",
    cantidad_puertas: "2",
    estantes_regulables: "Si",
    porta_vegetales: "Si",
    capacidad: "320 Litros",
    capacidad_freezer: "72 Litros",
    porta_botellas: "No",
    display: "Si",
    fabrica_hielo: "Si",
    dispenser_agua: "Si",
  },
  {
    id: 18,
    img: "https://i.ibb.co/rMyxDZq/Heladera-Samsung-Inox-380-L-Con-Display-RT38-K5932-SL.jpg",
    title: "Heladera Samsung Inox 380L Con Display RT38K5932SL",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "SAMSUNG",
    modelo: "RT38K5982SL/B3",
    capacidad: "394 L",
    inverter: "Sí",
    tipo_energia: "A+",
    deshielo: "No frost",
    freezer: "Superior",
    estantes_freezer: "1",
    fabrica_hielo: "Si",
    peso: "72 KG",
    dimensiones: "Ancho: 67.5cm Prof.: 66.8cm Alto: 178.5cm",
    niveles_temperatura: "5",
    porta_vegetales: "Si",
    porta_huevos: "Si",
    puertas: "2",
    display: "Si",
    sistema_air_flow: "Si",
    filtro_desodorizador: "Si",
  },
  {
    id: 19,
    img: "https://i.ibb.co/BBvMzwk/Heladera-Philco-Inox-530l-94phsb530xt.jpg",
    title: "Heladera Philco Inox 530l 94phsb530xt",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "PHILCO",
    modelo: "PHSB530XT",
    capacidad: "282 L",
    inverter: "No",
    tipo_energia: "A+",
    capacidad_freezer: "218 L",
    deshielo: "No frost",
    freezer: "Side by side",
    estantes_freezer: "2",
    fabrica_hielo: "No",
    peso: "99 Kg",
    dimensiones: "Ancho: 89,5cm Prof.: 74,5cm Alto: 178,8cm",
    porta_vegetales: "Sí",
    puertas: "2",
    display: "Sí",
    sistema_air_flow: "Sí",
  },
  {
    id: 20,
    img: "https://i.ibb.co/R0xKjJ0/Heladera-BRIKET-Bajo-Mesada.jpg",
    title: "Heladera BRIKET Bajo Mesada Colores",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    dimensiones: "Ancho: 55cm, Prof.: 62cm Alto: 85cm",
    peso: "3 Kg",
    capacidad: "146 Litros",
    tipo_energia: "A",
    porta_latas: "No",
    fabrica_hielo: "No",
    dispenser: "No",
    porta_vegetales: "Si",
  },
  {
    id: 21,
    img: "https://i.ibb.co/g6p4V0H/Freezer-Horizontal-Briket-FR-2500-st.jpg",
    title: "Freezer Horizontal Briket FR 2500 st",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "FR 2500",
    capacidad: "224 L",
    ruedas: "Si",
    funciones: "Enfriar, Freezar",
    tipo_energia: "B",
    peso: "50.1 Kg",
    dimensiones: "Ancho: 94,5cm Prof.: 70cm Ancho: 84cm",
    orientacion: "Horizontal",
    cantidad_puertas: "1",
  },
  {
    id: 22,
    img: "https://picsum.photos/200/300?random=10",
    title: "Freezer Horizontal Briket FR 3300 ST",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "FT 3300 ST",
    capacidad: "295 Litros",
    peso: "40 KG",
    dimensiones: "Alto: 84cm Prof.: 70cm Ancho: 115,5cm",
    orientacion: "Horizontal",
    cantidad_puertas: "1",
    cestos_deslizables: "Si",
    enfriador_botellas: "Si",
  },
  {
    id: 23,
    img: "https://i.ibb.co/8P8xJ2t/Freezer-Horizontal-Briket-FR-4500-ST-2-Puertas.jpg",
    title: "Freezer Horizontal Briket FR 4500 ST 2 Puertas",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "FR 4500",
    capacidad: "390 L",
    ruedas: "Sí",
    funciones: "Congelar, Conservar, Enfriar",
    tipo_energia: "A",
    peso: "64.4 KG",
    dimensiones: "Ancho: 148cm Prof.: 70cm Alto: 84cm",
    orientacion: "Horizontal",
    cantidad_puertas: "2",
    cantidad_cajones: "2",
  },
  {
    id: 24,
    img: "https://i.ibb.co/k6cGWnF/Exhibidora-Comercial-BRIKET-Master-3200.jpg",
    title: "Exhibidora Comercial BRIKET Master 3200",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    capacidad: "315 Litros",
    dimensiones: "Ancho: 55cm Prof.: 63cm Alto c/Cenefa: 185.5cm Alto s/Cenefa: 171cm",
    cantidad_puertas: "Triple vidrio Deshidratado entre sí",
    luz_interior: "Si",
    cantidad_estantes: "4 Intercambiables",
    motocompresor: "1/3 HP reforzado",
    niveles_temperatura: "de 0° a +5° C",
    otro: "Ideal para bebidas, lácteos, frutas, verduras, pastas, etc",
  },
  {
    id: 25,
    img: "https://i.ibb.co/HHgybCC/Exhibidora-Comercial-BRIKET-Master-4300.jpg",
    title: "Exhibidora Comercial BRIKET Master 4300",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    capacidad: "417 Litros",
    cantidad_estantes: "4",
    max_estante: "42 Kg",
    tipo_energia: "D",
    gas: "R 290",
    dimensiones: "Ancho: 65,5cm Prof.: 60cm Alto: 203cm",
    peso: "79 Kg",
  },
  {
    id: 26,
    img: "https://i.ibb.co/PYLQv7R/Exhibidora-Comercial-BRIKET-Master-5000.jpg",
    title: "Exhibidora Comercial BRIKET Master 5000",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    peso: "95 KG",
    dimensiones: "Ancho: 70cm Prof.: 62cm Alto: 208cm",
    capacidad: "501 Litros",
    cantidad_puertas: "Triple vidrio",
    cantidad_estantes: "4 Estantes Removibles",
    motocompresor: "1/3 Hp",
    niveles_temperatura: "0 a +5°C",
  },
  {
    id: 27,
    img: "https://i.ibb.co/dMVXvjY/Exhibidora-Comercial-Best-Cold-2-Puertas-750l-MT750.webp",
    title: "Exhibidora Comercial BestCold 2 Puertas 750l MT750",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "MT750",
    capacidad: "750 L",
    orientacion: "Vertical",
    luz_interior: "Sí",
    dimensiones: "Alto: 180cm Prof.: 65cm Ancho: 110cm",
    control_temperatura: "Sí",
    niveles_temperatura: "4 °C - 10 °C",
    cervecera: "Sí",
    cantidad_puertas: "2",
    tipo_puertas: "Batientes",
    descongelamiento: "Automatico",
    motocompresor: "1/3 hp",
  },
  {
    id: 28,
    img: "https://i.ibb.co/9wwKbfT/Freezer-Horizontal-BRIKET-Tapa-Vidrio-3300.jpg",
    title: "Freezer Horizontal BRIKET Tapa Vidrio 3300",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "EH 3300",
    capacidad: "295 L",
    orientacion: "Horizontal",
    cantidad_cajones: "2",
    ruedas: "Sí",
    dimensiones: "Alto: 95cm Prof.: 61cm Ancho 115.5cm",
    tipo_energia: "A",
    gas: "R134",
    motocompresor: "FF1-12HBK",
  },
  {
    id: 29,
    img: "https://i.ibb.co/0cffVH7/Freezer-Horizontal-Teora-550-L-TV-FH550-TV.jpg",
    title: "Freezer Horizontal TEORA 550L TV FH550TV",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "TEORA",
    modelo: "FH550TV",
    capacidad: "542 L",
    cantidad_puertas: "2",
    cantidad_cajones: "2",
    dimensiones: "Ancho: 162cm Prof.: 70cm Alto: 84cm",
    niveles_temperatura: "-18°C a +5°C",
    gas: "R-134a",
  },
  {
    id: 30,
    img: "https://i.ibb.co/1nY1FH9/Batea-Comercial-Best-Cold-Standard-Recta-2400-R.jpg",
    title: "Batea Comercial BestCold Standard Recta 2400-R",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "2400-R",
    dimensiones: "Alto: 135cm Prof.: 100cm Ancho: 240cm",
    tipo_gabinete: "Exterior en Chapa",
    termoformado: "Alto Impacto",
    mesa_trabajo: "Acero Inoxidable Brillante",
    luz_interior: "Si",
    gas: "R22",
    otro: "Ideal para Granja, Carniceria, Pescaderia",
  },
  {
    id: 31,
    img: "https://i.ibb.co/RNRTRdr/Vitrina-Mostrador-BESTCOLD-Winnipeg-610-L-1600-WE.jpg",
    title: "Vitrina Mostrador BESTCOLD Winnipeg 610L 1600WE",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "winnipeg 1200",
    capacidad: "240 L",
    orientación: "Horizontal",
    luz_interior: "Sí",
    dimensiones: "Alto: 113cm Prof.: 78cm Ancho: 120cm",
    control_temperatura: "Sí",
    niveles_temperatura: "2 °C - 10 °C",
    cervecera: "Sí",
    material: "Acero",
  },
  {
    id: 32,
    img: "https://i.ibb.co/gj4QR3W/Batea-Comercial-Best-Cold-standard-Vidrio-bajo-1300-rs.jpg",
    title: "Batea Comercial BestCold standard Vidrio bajo 1300-RS",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "1300-RS",
    orientación: "Horizontal",
    luz_interior: "Sí",
    control_temperatura: "Sí",
    niveles_temperatura: "2 °C - 10 °C",
    material: "Acero"
  },
  {
    id: 33,
    img: "https://i.ibb.co/7kM7Cwj/Vitrina-Best-Cold-Winnipeg-Dark-1400-WE.jpg",
    title: "Vitrina BestCold Winnipeg Dark 1400WE",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "Winnipeg Dark 1400WE",
    mesa_trabajo: "Acero Inoxidable",
    termoformado: "Alto impacto",
    cantidad_estantes: "3",
    tipo_puertas: "Batientes Automáticas",
    luz_interior: "Si",
    niveles_temperatura: "2º a 6º c",
    motocompresor: "Embraco 1/4 HP",
    dimensiones: "Ancho: 140 cm. Prof.: 75 cm. Alto: 119 cm",
  },
  {
    id: 34,
    img: "https://i.ibb.co/gy6d8R9/Vitrina-con-Bajada-Best-Cold-450-L-1700-E.jpg",
    title: "Vitrina con Bajada BestCold 450L 1700E",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BEST COLD",
    modelo: "2100E",
    dimensiones: "Alto: 113cm Prof.: 78cm Ancho: 210cm",
    mesa_trabajo: "Acero Inoxidable",
    termoformado: "Alto Impacto",
    tipo_puertas: "Batientes",
    control_temperatura: "Digital con Descongelamiento Automatico",
    luz_interior: "Si, Tecnologia LED",
  },
  {
    id: 35,
    img: "https://i.ibb.co/Xs77jkx/Lavarropas-Drean-Next-8-12-ECO.jpg",
    title: "Lavarropas Drean Next 8.12 ECO",
    price: "$00,00",
    category: "lavarropas",
    marca: "DREAN",
    modelo: "8.12 ECO",
    velocidad_centrifugado: "1200 rpm",
    centrifugado: "Sí",
    velocidad_centrifugado: "Sí",
    centrifugado_autoequilibrado: "Sí",
    peso: "71 KG",
    dimensiones: "Alto:	85cm Prof.:	55cm Ancho:	60cm",
    filtro: "Sí",
    tambores: "1 de Acero Inoxidable",
    tipo_lavarropas: "Automatico",
    carga: "Frontal",
    tipo_energia: "A++",
    capacidad: "8 KG",
    lavasecarropas: "No",
    inverter: "No",
    smartphone: "No",
    alarma_final: "Si",
    wifi: "No",
    display: "Si, LED",
    tegnologia: "ECO",
    niveles_temperatura: "Fría, 30°C, 40°C, 60°C, 70°C",
    cantidad_programas: "34",
    tipo_bloqueo: "Bloqueo Panel, Bloqueo Seguridad de Puerta",
    otro: "Lavado Rapido, Funcion Antiarrugas",
  },
  {
    id: 36,
    img: "https://i.ibb.co/cgYJ1mC/Lavasecarropas-Electrolux-8kg-inverter-EWD08-B.png",
    title: "Lavasecarropas Electrolux 8kg inverter EWD08B",
    price: "$00,00",
    category: "lavarropas",
    marca: "ELECTROLUX",
    modelo: "EWD08B",
    dimensiones: "Alto: 85cm Prof.: 57.5cm Ancho: 60cm",
    lavasecarropas: "Sí",
    capacidad_secado: "5 Kg",
    inverter: "Si",
    capacidad: "8 kg",
    carga: "Frotal",
    tipo_energia: "A",
    velocidad_centrifugado: "1200 rpm",
    centrifugado: "Si",
    centrifugado_autoequilibrado: "Si",
    peso: "62.2 kg",
    filtro: "Si",
    tambor: "1, de Acero Inoxidable",
    display: "Si, tipo LED",
    tipo_bloqueo: "Bloqueo de Panel, Bloqueo de Seguridad de Puerta",
    otro: "Funcion Antiarrugas",
  },
  {
    id: 37,
    img: "https://i.ibb.co/D4gfFgd/Lavarropas-Drean-Concept-Fuzzy-Logic-Tech-V1.jpg",
    title: "Lavarropas Drean Concept Fuzzy Logic Tech V1",
    price: "$00,00",
    category: "lavarropas",
    marca: "DREAN",
    modelo: "Fuzzy Logic Tech V1",
    lavasecarropas: "No",
    carga: "Superior",
    tipo_energia: "B",
    capacidad: "5 Kg",
    inverter: "No",
    velocidad_centrifugado: "500 rpm",
    centrifugado: "Si",
    centrifugado_autoequilibrado: "No",
    dimensiones: "Alto: 89cm Prof.: 54cm Ancho: 54cm",
    peso: "33.6 kg",
    cantidad_programas: "15",
    tipo_lavarropas: "Automatico",
    niveles_temperatura: "Fría, Tibia, Caliente",
    filtro: "Si",
    tambor: "1, Polycron",
    display: "Si",
    tipo_bloqueo: "Bloqueo de Puerta",
    otro: "Lavado Rapido, Funcion Antiarrugas",
  },
  {
    id: 38,
    img: "https://i.ibb.co/HqYQFrS/Secarropas-Koh-i-Noor-Negro-N-655-2-5-5-KG.jpg",
    title: "Secarropas Koh i Noor Negro N-655-2 5.5KG",
    price: "$00,00",
    category: "lavarropas",
    marca: "KOH I NOOR",
    modelo: "N-655",
    capacidad: "5.5 kg",
    tambor: "1, de Acero Inoxidable",
    secado: "Centrifugo",
    carga: "Superior",
    dimensiones: "Alto: 63.5cm Diametro: 34.3cm",
    velocidad_centrifugado: "2800 rpm",
    sistema_traba: "Maxima Seguridad TBS",
    tapa: "Abre sola cuando deja de Girar el Tambor",
    otro: "Manija para Transportar, Patas de muy buena sujecion",
    telas: "Algodon, Lana, Toalla, Jean, Lycra, Sintetico, Polyester, etc.",
  },
  {
    id: 39,
    img: "https://i.ibb.co/TLJq7Qc/Secarropas-Koh-i-Noor-Acero-A-665-2-6-5-KG.jpg",
    title: "Secarropas Koh i Noor Acero A-665-2 6.5KG",
    price: "$00,00",
    category: "lavarropas",
    marca: "KOH I NOOR",
    modelo: "A-665",
    capacidad: "6.5 Kg",
    tambor: "1, de Acero Inoxidable",
    carga: "Superior",
    dimensiones: "Alto: 69.5cm Prof.: 34.3cm Ancho: 34.3cm",
    velocidad_centrifugado: "2800 rpm",
    sistema_traba: "Maxima Seguridad TBS",
    tapa: "Abre sola cuando deja de Girar el Tambor",
    otro: "Manija para Transportar, Patas de muy buena sujecion",
    telas: "Algodon, Lana, Toalla, Jean, Lycra, Sintetico, Polyester, etc.",
  },
  {
    id: 40,
    img: "https://i.ibb.co/7zRQrsD/Cocina-Vitta-Bella-Bianca-Multigas.jpg",
    title: "Cocina Vitta Bella Bianca Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Bianca",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 41,
    img: "https://i.ibb.co/ChMQmbG/Cocina-Vitta-Bella-Nera-Multigas.jpg",
    title: "Cocina Vitta Bella Nera Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Nera",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 42,
    img: "https://i.ibb.co/pxFrvGj/Cocina-Vitta-Bella-Acero-Multigas.jpg",
    title: "Cocina Vitta Bella Acero Multigas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Acero",
    cantidad_hornallas: "4",
    otro: "Mejor Calidad - Mayor durabilidad - Diseño Innovador",
    tipo: "Multigas",
    dimensiones: "Alto: 86cm Prof: 55cm Ancho: 51cm",
    puertas: "Vidrio Templado",
    estilo: "Enlozado con Manija de Hierro de Facil Limpieza",
  },
  {
    id: 43,
    img: "https://i.ibb.co/0y57wXV/Cocina-Vitta-Semi-Industrial-Bella-Chef.jpg",
    title: "Cocina Vitta Semi Industrial Bella Chef",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "VITTA",
    modelo: "Bella Chef - Semi Industrial",
    dimensiones: "Alto 86cm, Prof.: 58cm Ancho: 55cm",
    piso: "Ladrillo Refractario",
    puertas: "Vidrio Templado",
    estilo: "Rejas de Fundicion, Acero Inoxidable Esmerilado con Pirometro en Puerta",
  },
  {
    id: 44,
    img: "https://i.ibb.co/Trp8wGz/Cocina-Electrolux-Doble-Horno-Elec-Gas.jpg",
    title: "Cocina Electrolux Doble Horno Elec-Gas",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "ELECTROLUX",
    modelo: "56DXQ",
    grill: "No",
    temporizador: "Si",
    comando_tactil: "No",
    horno_autolimpiante: "No",
    cantidad_hornallas: "4",
    peso: "46.5 kg",
    dimensiones: "Alto: 146.5cm Ancho: 56cm Prof.: 107.4cm",
    alimentacion: "Gas y Electrica",
    industrial: "No",
    capacidad_horno: "106.5 Litros",
    horno_doble: "Si",
    temporizador: "Si",
    parrillas: "3",
    tipo_energia: "A",
    tapa: "Si",
  },
  {
    id: 45,
    img: "https://i.ibb.co/BgH66Jw/Cocina-Industrial-Motta-Pro-Pv-520-G-N.jpg",
    title: "Cocina Industrial Motta Pro Pv 520 G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "MOTTA",
    modelo: "MO520PVN",
    dimensiones: "Alto: 86cm Prof.: 55cm Ancho: 53cm",
    cantidad_hornallas: "4",
    puertas: "Vidrio Color Negro",
    grill: "Si, Inferior",
    otro: "Rejas de Fundicion, Exterior de Acero Inox. interior Enlozado",
    parrillas: "2",
  },
  {
    id: 46,
    img: "https://i.ibb.co/yhf9DCf/Cocina-Industrial-Motta-Pro-600-Negra-G-N.jpg",
    title: "Cocina Industrial Motta Pro 600 Negra G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "MOTTA",
    modelo: "Pro 600 Negra G-N",
    dimensiones: "Alto: 86cm Prof.: 64cm Ancho: 59cm",
    cantidad_hornallas: "4",
    puertas: "Vidrio Color Negro",
    grill: "Si, Inferior",
    otro: "Rejas de Fundicion, Exterior de Acero Inox. interior Enlozado",
    parrillas: "2",
  },
  {
    id: 47,
    img: "https://i.ibb.co/5jXGPdX/Cocina-Industrial-Compacta-El-Gauchito-G-N.jpg",
    title: "Cocina Industrial Compacta El Gauchito G-N",
    price: "$00,00",
    category: "cocinas y hornos",
    marca: "EL GAUCHITO",
    modelo: "550",
    industrial: "Si",
    cantidad_hornallas: "4",
    valvula_seguridad: "Si",
    tapa: "No",
    puerta_horno: "Ciega",
    horno_doble: "No",
    temporizador: "No",
  },
  {
    id: 48,
    img: "https://i.ibb.co/5cMQKMT/Horno-Electrico-Vitta-Forno-blanco-45l-c-Anafe.jpg",
    title: "Horno Electrico Vitta Forno blanco 45l c-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno Bianco",
    capacidad_horno: "45 Litros",
    potencia: "1600 W",
    dimensiones: "Alto: 35cm, Prof.: 38cm, Ancho: 54cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 49,
    img: "https://i.ibb.co/qYT4vS3/Horno-Vitta-Electrico-DW-5094-CA-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico DW-5094CA 55L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno NERO",
    capacidad_horno: "55 Litros",
    potencia: "2000 W",
    dimensiones: "Alto: 37cm, Prof.: 42cm, Ancho: 56cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
    otro: "Pizza Bump",
  },
  {
    id: 50,
    img: "https://i.ibb.co/qYT4vS3/Horno-Vitta-Electrico-DW-5094-CA-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico DW-7004CA 70L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno NERO",
    capacidad_horno: "70 Litros",
    potencia: "2080 W",
    dimensiones: "Alto: 39cm, Prof.: 46cm, Ancho: 58cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
    otro: "Pizza Bump",
  },
  {
    id: 51,
    img: "https://i.ibb.co/LxQW8jG/Horno-Vitta-Electrico-Forno-Rosso-45-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico Forno Rosso 45L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno ROSSO",
    capacidad_horno: "45 Litros",
    potencia: "1600 W",
    dimensiones: "Alto: 35cm, Prof.: 38cm, Ancho: 54cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 52,
    img: "https://i.ibb.co/8BdkZhH/Horno-Vitta-Electrico-Forno-Rosso-55-L-C-Anafe.jpg",
    title: "Horno Vitta Electrico Forno Rosso 55L C-Anafe",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "Forno ROSSO",
    capacidad_horno: "55 Litros",
    potencia: "2000 W",
    dimensiones: "Alto: 37cm, Prof.: 42cm, Ancho: 56cm",
    niveles_temperatura: "250 Cº",
    anafe: "Doble",
  },
  {
    id: 53,
    img: "https://i.ibb.co/MnM0KvS/Horno-Vitta-Electrico-40l-VIT-HE4000012000-RC-1.jpg",
    title: "Horno Vitta Electrico 40l-50l-65l",
    price: "$00,00",
    category: "pequeños cocina",
    marca: "VITTA",
    modelo: "HE4000- HE5000- HE6500",
    capacidad: "40 Litros, 50 Litros & 65 Litros",
    funcion: "Espiedo",
    anafe: "Doble",
    potencia:"2000W",
    niveles_temperatura:"250 Cº",
    otro: "Incluye Bandeja y 2 Pinzas",
  },
  {
    id: 54,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 55,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 56,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 57,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 58,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 59,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 60,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 61,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 62,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 63,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 64,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 65,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 66,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 67,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 68,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 69,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
  {
    id: 70,
    img: "",
    title: "",
    price: "$00,00",
    category: "",
    marca: "",

  },
];

export default function getItems() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(data);
    }, 2000);
  });
}

export function getItemsSingle(idItem) {
  return new Promise((resolve, reject) => {
    let itemFind = data.find((item) => {

      return item.id === parseInt(idItem);
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}

export function getItemsByCategory(cat) {
  return new Promise((resolve, reject) => {
    let itemFind = data.filter((item) => {
      return item.category === cat;
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}


