const data = [
  {
    id: 1,
    img: "https://i.ibb.co/0QbcYBS/Aire-acondicionado-Split-Kanji-2600w-f-c-26fkht81.jpg",
    title: "Aire Acondicionado Split KANJI 2600w FC",
    price: "$00.00",
    category: "aire",
    marca: "KANJI",
    modelo: "26FKHT81",
    deflectoresmoviles: "Sí",
    frigorias: "2240",
    display: "No",
    timer: "Sí",
    automatico: "Si",
    sleep: "Sí",
    ventilacion: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    contro: "Sí",
    inverter: "No",
    gas: "R-410a",
  },
  {
    id: 2,
    img: "https://i.ibb.co/pKCPbxc/aire-acondicionado-split-hitachi-2600w-fc.jpg",
    title: "Aire Acondicionado Split HITACHI 2600w FC",
    price: "$00,00",
    category: "aire",
    marca: "HITACHI",
    tipo_equipo: "Split",
    frio_calor: "Sí",
    frigorias: "2499",
    gas: "R410A",
    tipo_energia: "A",
    automático: "Sí",
    deshumificación: "Sí",
    sleep: "Sí",
    medidasSplit: "27,5cm Alto - 85cm Ancho - 32cm Prof.",
    peso: "11 kg",
    medidasMotor: "54,5cm Alto - 70cm Ancho - 30cm Prof.",
    pesoMotor: "27 kg",
    control: "Sí",
  },

  {
    id: 3,
    img: "https://i.ibb.co/g9mKHqb/aire-acondicionado-split-kanji-3200w-fc.jpg",
    title: "Aire acondicionado Split KANJI 3200w FC",
    price: "$00,00",
    category: "imagen",
    marca: "KANJI",
    display: "No",
    deflectores_moviles: "Sí",
    frigorias: "2760",
    timer: "Sí",
    automatico: "Sí",
    sleep: "Sí",
    ventilación: "Sí",
    frio_calor: "Sí",
    tipo_equipo: "Split",
    tipo_energia: "A",
    control: "Sí",
    inverter: "No",
    gas: "R-410a",
  },
  {
    id: 4,
    img: "https://i.ibb.co/r67MbZ3/aire-acondicionado-inverter-greenstay-fc-3500.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 3500w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "3010",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
  },
  {
    id: 5,
    img: "https://i.ibb.co/HHG7r1D/aire-acondicionado-inverter-greenstay-fc-6900.jpg",
    title: "Aire acondicionado Inverter GREENSTAY 6900w FC",
    price: "$00,00",
    category: "aire",
    marca: "GREENSTAY",
    frigorias: "5934",
    tipo_equipo: "Split Inverter",
    frío_calor: "Si",
    tipo_energia: "A+",
    gas: "R-410A",
  },
  {
    id: 6,
    img: "https://i.ibb.co/TLkWf51/ventilador-vitta-18pulgadas-3-en-1-90w.jpg",
    title: "Ventilador VITTA 18'' 3 en 1 90w",
    price: "$00,00",
    category: "ventilacion",
    marca: "VITTA",
    dimensiones: "46cm",
    tipo_ventilador: "Mesa, Pared, Pie",
    potencia: "90 w",
    velocidades: "3",
    aspas: "Metal",
    cantidad_aspas: "3",
  },
  {
    id: 7,
    img: "https://i.ibb.co/7V2dS40/ventilador-industrial-vitta-30-Pulgadas-2-en-1.jpg",
    title: "Ventilador Industrial Vitta 30'' 2 en 1",
    price: "$00,00",
    category: "ventilacion",
    marca:  "VITTA",
    tipo_ventilador: "Pared, Pie",
    cantidad_aspas: "3",
    velocidades: "3",
    altura: "1,4 metros",
    potencia: "180W",
    aspas: "Plásticas",
  },

  {
    id: 8,
    img: "https://i.ibb.co/N6LrtJg/Ventilador-18-Pulgadas-3-en-1-STAR-TRAK.jpg",
    title: "Ventilador 18'' 3 en 1 STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca:  "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Metal",
    potencia: "90W",
  },
  {
    id: 9,
    img: "https://i.ibb.co/MgJGJFf/Ventilador-Pie-14-Pulgadas-Base-Pesada-STAR-TRAK.jpghttps://picsum.photos/200/300?random=9",
    title: "Ventilador Pie 14'' Base Pesada STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos"
  },
  {
    id: 10,
    img: "https://i.ibb.co/WBR7xrp/Ventilador-Pie-14-Pulgadas-STAR-TRAK-Multi.jpg",
    title: "Ventilador Pie 14'' STAR TRAK Multi",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Pared, Turbo, Pie",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,50 metros",
    potencia: "90W",
    otro: "Repele Mosquitos",
  },
  {
    id: 11,
    img: "https://i.ibb.co/kcJYp06/Ventilador-14-Pulgadas-STAR-TRAK.jpg",
    title: "Ventilador 20'' STAR TRAK",
    price: "$00,00",
    category: "ventilacion",
    marca: "STAR TRAK",
    tipo_ventilador: "Fijo",
    velocidades: "3",
    cantidad_aspas: "5",
    aspas: "Plasticas",
    altura: "1,70 Metros",
    potencia: "120W",
    otro: "Repele Mosquitos",
  },
  {
    id: 12,
    img: "https://i.ibb.co/bdQqNYr/Climatizador-Philco-Portatil-7-L.jpg",
    title: "Climatizador Philco Portatil 7L",
    price: "$00,00",
    category: "calefaccion",
    marca: "PHILCO",
    velocidades: "3",
    tipo_equipo: "Oscilación",
    otro: "No requiere instalación",
    flujo_aire: "600 m3/h",
    cantidad_agua: "7 Lts (5 Lts con los cubos de hielo reutilizables)",
    detalles: "Indicador de nivel de agua",
    timer: "No",
    peso: "6,6 kgs",
    dimesion: "Alto: 70 cm Ancho: 28 cm Prof: 26,5 cm",
  },
  {
    id: 13,
    img: "https://i.ibb.co/B2h9Vv3/Climatizador-Kanji-LRG04-11-CR-Frio-Calor.jpg",
    title: "Climatizador Kanji LRG04-11CR Frio Calor",
    price: "$00,00",
    category: "calefaccion",
    marca: "KANJI",
    velocidades: "3",
    frio_calor: "Si",
    control: "Si",
    cantidad_agua: "8 Litros",
    dimensiones: "Alto 70 cm Ancho 37 cm Prof: 29 cm",
  },
  {
    id: 14,
    img: "https://i.ibb.co/nL5qRNX/Heladera-Briket-322-L-BK2-F-1610-Blanca-Gris-Negro.jpg",
    title: "Heladera Briket 322L BK2F 1610 Blanca-Gris-Negro",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    modelo: "BK2F 1610",
    color: "Blanco, Gris o Negro",
    freezer: "Superior",
    estantes_freezer: "1",
    dimensiones: "Ancho: 66cm Altura: 164cm Prof: 682cm",
    estantes_heladera: "3",
    dispenser_agua: "No",
    dispenser_hielo: "No",
    luz_interior: "Si",
    cantidad_puertas: "2",
    inverter: "No",
    tipo_energia: "A+",
    capacidad: "322 Litros",
    congelador: "No",
    vegetales: "Si",
    porta_botellas: "No",
    porta_latas: "No",
    porta_huevos: "Si",    
  },
  {
    id: 15,
    img: "https://i.ibb.co/F0wyRpN/Heladera-Briket-476-L-BK2-F-2121-Gris.jpg",
    title: "Heladera Briket 476L BK2F 2121 Gris",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "BRIKET",
    Modelo:"BK2F 2121",
    dimensiones: "Ancho: 66cm x Prof: 75cm x Alto: 189 cm",
    inverter: "No",
    tipo_energia: "A+",    
    deshielo: "Manual",
    freezer: "Superior",
    luz_interior: "Sí",
    puertas: "2",
  },
  {
    id: 16,
    img: "https://i.ibb.co/1X2pcjr/Heladera-SIAM-Top-Mount-370l-C-Disp-inox.jpg",
    title: "Heladera SIAM Top Mount 370l C-Disp inox",
    price: "$00,00",
    category: "heladeras y freezer",
    marca: "SIAM",
    modelo: "HSI-NT30XD",
    estilo: "Acero inoxidable",
    freezer: "Superior",
    estantes_freezer: "1",
    fabrica_hielo: "Si",
    peso: "68 Kg",
    dimensiones: "Ancho: 69.6cm Prof: 68.5cm Alto: 171.2cm",
    estantes_heladera: "3",
    dispenser_agua: "Si",
    dispenser_hielo: "Si",
    luz_interior: "Si",
    inverter: "Si",
    deshielo: "No Frost",
    tipo_energia: "A",
    capacidad: "404 Litros",
    niveles_temperatura: "6",
    porta_vegetales: "Si",
    cantidad_puertas: "2",
    display: "No",        
  },
  {
    id: 17,
    img: "https://picsum.photos/200/300?random=10",
    title: "titulo 10",
    price: "$00,00",
    category: "imagen",
    // category: "Climatización",
    detail: "STOCK DISPONIBLE"
  },
  {
    id: 18,
    img: "https://picsum.photos/200/300?random=10",
    title: "titulo 10",
    price: "$00,00",
    category: "imagen",
    // category: "Climatización",
    detail: "STOCK DISPONIBLE"
  },
  {
    id: 19,
    img: "https://picsum.photos/200/300?random=10",
    title: "titulo 10",
    price: "$00,00",
    category: "imagen",
    // category: "Climatización",
    detail: "STOCK DISPONIBLE"
  },
  {
    id: 20,
    img: "https://picsum.photos/200/300?random=10",
    title: "titulo 10",
    price: "$00,00",
    category: "imagen",
    // category: "Climatización",
    detail: "STOCK DISPONIBLE"
  },

];

export default function getItems() {
  return new Promise((resolve, reject) => {
    setTimeout(() => {
      resolve(data);
    }, 2000);
  });
}

export function getItemsSingle(idItem) {
  return new Promise((resolve, reject) => {
    let itemFind = data.find((item) => {

      return item.id === parseInt(idItem);
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}

export function getItemsByCategory(cat) {
  return new Promise((resolve, reject) => {
    let itemFind = data.filter((item) => {
      return item.category === cat;
    });

    setTimeout(() => {
      if (itemFind) resolve(itemFind);
      else reject(new Error("Item no encontrado"));
    }, 2000);
  });
}


